### ISSUE TITLE
K8s scanner wont connect to router with 404 even with an admin key

### ISSUE THREAD

**Issue by pedro-castro-koerber** [deepfence/ThreatMapper#1028]
After deploying the k8s scanner (with deepfence-k8s-scanner helm chart) with the following values

`image:
  tag: "1.5.0"
#managementConsoleUrl: "10.4.66.46"
managementConsoleUrl: "deepfence-router.threatmapper.svc.cluster.local"
deepfenceKey: "ADMIN KEY"
clusterName: "kdtools"
`

The scanner always gives the same error 

`
time="2023-04-20 13:35:37" level=debug msg="Token generated successfully" file="main.go:61"

time="2023-04-20 13:36:07" level=debug msg="{\"data\":{\"scans\":{\"7b75a386-9850-4e07-aac8-6003ba940582_2023-04-20T12:02:30.000\":{\"scan_id\":\"7b75a386-9850-4e07-aac8-6003ba940582_2023-04-20T12:02:30.000\",\"account_id\":\"7b75a386-9850-4e07-aac8-6003ba940582\",\"scan_type\":\"nsa-cisa\",\"controls\":null}},\"refresh\":\"\"}}" file="main.go:108"

time="2023-04-20 13:36:07" level=info msg="scanId: 7b75a386-9850-4e07-aac8-6003ba940582_2023-04-20T12:02:30.000 scanType: nsa-cisa status: INPROGRESS" file="main.go:177"

time="2023-04-20 13:37:03" level=error msg="Unable to complete request on https://deepfence-router.threatmapper.svc.cluster.local/ingest/topics/compliance-scan-logs. Got 404 - <!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /ingest/topics/compliance-scan-logs</pre>\n</body>\n</html>\n" file="main.go:116"

time="2023-04-20 13:39:46" level=debug msg="Number of docs to ingest: 0" file="main.go:202"`

The token used is an admin token. The URL is reached from what I can understand (the url is the svc of the router since its inside the same cluster for testing purposes

1. Install threatmapper in k8s with ingress controller
2. Install deepfence-k8s-scanner
3. Use admin key

**Expected behavior**
For the injector to connect and generate a NSA and CISA report

**Screenshots**
<img width="1595" alt="Screenshot 2023-04-20 at 14 43 29" src="https://user-images.githubusercontent.com/96879853/233385222-8391eab5-cce7-4bd7-94a7-733e46bf5397.png">
<img width="900" alt="Screenshot 2023-04-20 at 14 43 41" src="https://user-images.githubusercontent.com/96879853/233385274-4a20f11b-effa-4ba1-ab05-59430031543b.png">

**Comment by shyam-dev** [comment]
Hello @pedro-castro-koerber  - Can you upgrade the threatmapper and check ? https://github.com/deepfence/ThreatMapper/tree/release-1.5/deployment-scripts
