### ISSUE TITLE
[v2] Slow UI with high number of nodes (topology)

### ISSUE THREAD

**Issue by noboruma** [deepfence/ThreatMapper#1110]
With high number of nodes on topology graph view, the browser stops loading the tab as it's too slow to render (~25k nodes).
On the other hand, the table API view API is fast.
We probably want to add some logic on the UI to disable slow features when we reach a certain count & go directly to paginated UXes

**Comment by sandman137** [comment]
Makes sense. At that scale the graphs will anyway get way too hairy. Alternatively, the UI should not try to display everything at scale, rather just summary nodes that can be expanded into a searchable list on the side panel.

**Comment by manV** [comment]
I like the idea to just have the table view for large number of nodes. Table view is filterable and it would be equivalent to @sandman137's suggestion of having a filterable list in side panel. The question is what number of nodes should be considered a limit? the ability to show large number of nodes varies depending of resources of the machine the browser is running on.

**Comment by shyam-dev** [comment]
Anything more than 200 will make it hard to see in the UI. That can be a possible number beyond which we default to table view
