### ISSUE TITLE
[v2] Need host level filter for containers and pods

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1119]
**Additional context**
In topology page containers and pods dont have filters, filter by host will be a good option to narrow down to required container

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/7c35934c-ff14-4e49-889d-e962eea09741)

**Components/Services**
- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by shyam-dev** [comment]
As a first step add host filters.
