### ISSUE TITLE
unrecognized import path "gopkg.in/yaml.v2" while building script

### ISSUE THREAD

**Issue by armorvx** [deepfence/ThreatMapper#114]
**Description of console out while building with ./build.sh**

+ bash /home/deepfence/check-deps.sh
unrecognized import path "gopkg.in/yaml.v2": reading https://gopkg.in/yaml.v2?go-get=1: 502 
        server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://nt.Timeout exceeded while awaiting headers)
+ build_result=1
+ '[' 1 -ne 0 ']'
+ echo 'Dependencies installation failed, bailing out'
Dependencies installation failed, bailing out
+ exit 1
Deepfence code compilation failed, bailing out
Building agent image failed. Exiting

**To Reproduce**
1. git clone https://github.com/deepfence/ThreatMapper.git
2. going into directory ThreatMapper
3. ./build.sh

This error message occurs in step 8/( for WORKDIR $DF_GENT_SRC
Is there any report for that for solving. 

Thanks & Regards

**Comment by ramanan-ravi** [comment]
Hi @armorvx,

Currently https://gopkg.in/yaml.v2 is timing out.
Please try after few hours.
Once that server is up, build should work.

**Comment by armorvx** [comment]
Nice to know.

Thanks
