### ISSUE TITLE
deepfence_agent_ce:latest on armv7 docker

### ISSUE THREAD

**Issue by armorvx** [deepfence/ThreatMapper#120]
Maybe this isn't really a bug, but maybe an configuration or compatibility issue. The sensor must be install on external chip set devices they are in a network comparison. Basic for this is armV7.

The package installation in dependencies  was installing docker.io on armv7.
Which image or where can find the armV7 deploy image for ?

1. try to deploy the deepfence_agent_ce:latest on armv7 with following script
2. See error

`
docker run -dit --cpus=".2" --name=deepfence-agent --restart on-failure --pid=host --net=host \
  --privileged=true -v /sys/kernel/debug:/sys/kernel/debug:rw -v /var/log/fenced \
  -v /var/run/docker.sock:/var/run/docker.sock -v /:/fenced/mnt/host/:ro \
  -e USER_DEFINED_TAGS="" -e MGMT_CONSOLE_URL="XXX.XXX.XXX.XXX" -e MGMT_CONSOLE_PORT="443" \
  -e DEEPFENCE_KEY="API-KEY" \
  deepfenceio/deepfence_agent_ce:latest
`
Result:
`
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
`
**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [x] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by armorvx** [comment]
for extending these topic.. docker image deepfence_agent_ce:latest is installed correctly, but is continuously restarting : 

` 107f461d726c   deepfenceio/deepfence_agent_ce:latest   "/usr/local/bin/star…"   21 minutes ago   Restarting (1) Less than a second ago             deepfence-agent
`
restart procedure run 60 seconds in a while, and starts again 

Best Regards

**Comment by shyam-dev** [comment]
Hello @armorvx - armv7 is not a supported architecture (yet). Feel free to submit a patch that will help compile the code for armv7 architectures.

**Comment by sandman137** [comment]
@armorvx assuming you already compiled agent image for arm v7? Please share logs. 

Btw, you do not have to compile console images to armv7, that would be too much work and not required as long as you can run console on x86. Just compiling agent for armv7 should do the job.

**Comment by armorvx** [comment]
lets write some steps for starting in for deepfence_agent image for arm compiling... how you would start or what you think is the best practice ?

**Comment by armorvx** [comment]
i´am trying first to extract all files from deepfence_agent_ce_latest. Any steps for going on with next and a idea for a practicable image container @sandman137 and @shyam-dev ?

Best Regards

**Comment by sandman137** [comment]
@mukuldeepfence is checking this out, he should be able to share steps.

**Comment by shyam-dev** [comment]
Hello @armorvx The place to start is the script build.sh inside the deepfence_agent directory. There is a makefile that builds the core visualization componenet. The code is completely in golang and hence, you need to modify the "go build" command to "env GOOS=linux GOARCH=armv7 go build". This will build the binaries for armv7 architectures running linux.

Feel free to post the results of the command here, or join our slack channel and send out a message. We will help you get this up & running on armv7.

**Comment by armorvx** [comment]
I thought I start with this build.sh on Raspberry Pi with an installed Raspbian booster image, which was made and installed by noobs. 

The necessary changes are done like described above in build.sh for directory deepfence_agent.

`env GOOS=linux GOARCH=armv7 go build"`

Take a look about these please after the build.sh...

`
Building Scope
/bin/sh: 1: go: not found
#env GOGC=off  go clean ./...
rm -rf scope.tar .scope_ui_build.uptodate .cache/build_node_modules/.uptodate .scope_backend_build.uptodate \
        prog/deepfence_exe vendor/github.com/peterbourgon/runsvinit/runsvinit prog/staticui/staticui.go prog/externalui/externalui.go client/build/*.js client/build-external/*.js docker/weave .pkg \
        report/report.codecgen.go render/detailed/detailed.codecgen.go vendor/github.com/ugorji/go/codec/codecgen/bin
rm -rf docker/deepfence*
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
rm -rf .cache/build_node_modules .cache/build_node_modules/../go-build
sudo rm -rf /opt/deepfence_agent/tools/apache/scope/.go
docker rmi -f weaveworks/scope-ui-build weaveworks/scope-backend-build \
        weaveworks/scope weaveworks/cloud-agent \
        weaveworks/scope: weaveworks/cloud-agent: \
        weaveworks/weaveexec:2.1.3 \
        ubuntu:bionic alpine:3.11 node:6.9.0 2>/dev/null || true
/bin/sh: 1: go: not found
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
fatal: Kein Git-Repository (oder irgendeines der Elternverzeichnisse): .git
docker build -t weaveworks/scope-backend-build backend
Sending build context to Docker daemon  6.144kB
Step 1/12 : FROM golang:1.13.9
 ---> 92cd67b537b8
Step 2/12 : ENV SCOPE_SKIP_UI_ASSETS true
 ---> Using cache
 ---> e005783fe6dc
Step 3/12 : RUN set -eux;    export arch_val="$(dpkg --print-architecture)";    apt-get update &&    if [ "$arch_val" = "amd64" ]; then      apt-get install -y libpcap-dev time file shellcheck git gcc-arm-linux-gnueabihf curl build-essential python-pip;    else      apt-get install -y libpcap-dev time file shellcheck git curl build-essential python-pip;    fi;       rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Using cache
 ---> c8f671e99ad0
Step 4/12 : RUN go clean -i net &&      go install -tags netgo std &&    export arch_val="$(dpkg --print-architecture)";    if [ "$arch_val" != "ppc64el" ]; then    go install -race -tags netgo std;    fi;     go get -tags netgo                 golang.org/x/lint/golint             github.com/kisielk/errcheck             github.com/mjibson/esc          github.com/client9/misspell/cmd/misspell && chmod a+wr --recursive /usr/local/go &&  rm -rf /go/pkg/ /go/src/
 ---> Using cache
 ---> 29d63abacd6b
Step 5/12 : RUN export arch_val="$(dpkg --print-architecture)";    if [ "$arch_val" = "amd64" ]; then      curl -fsSL -o shfmt https://github.com/mvdan/sh/releases/download/v1.3.0/shfmt_v1.3.0_linux_amd64 &&      chmod +x shfmt &&      mv shfmt /usr/bin;    fi;
 ---> Using cache
 ---> af13e8a76f7e
Step 6/12 : RUN pip install yapf==0.16.2 flake8==3.3.0 requests==2.19.1
 ---> Using cache
 ---> 31a020802183
Step 7/12 : ENV DOCKERVERSION=17.09.1-ce
 ---> Using cache
 ---> 72b41a924069
Step 8/12 : RUN export arch_val="$(dpkg --print-architecture)";     if [ "$arch_val" = "arm64" ]; then         curl -fsSLO https://download.docker.com/linux/static/stable/aarch64/docker-${DOCKERVERSION}.tgz;     elif [ "$arch_val" = "amd64" ]; then         curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz;     elif [ "$arch_val" = "ppc64el" ]; then         curl -fsSLO https://download.docker.com/linux/static/stable/ppc64le/docker-${DOCKERVERSION}.tgz;     else         echo "No Docker client found for architecture $(arch_val)." &&         exit 1;     fi;     tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker &&     rm docker-${DOCKERVERSION}.tgz;
 ---> Running in eb71da405616
/bin/sh: 1: arch_val: not found
No Docker client found for architecture .
The command '/bin/sh -c export arch_val="$(dpkg --print-architecture)";     if [ "$arch_val" = "arm64" ]; then         curl -fsSLO https://download.docker.com/linux/static/stable/aarch64/docker-${DOCKERVERSION}.tgz;     elif [ "$arch_val" = "amd64" ]; then         curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz;     elif [ "$arch_val" = "ppc64el" ]; then         curl -fsSLO https://download.docker.com/linux/static/stable/ppc64le/docker-${DOCKERVERSION}.tgz;     else         echo "No Docker client found for architecture $(arch_val)." &&         exit 1;     fi;     tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker &&     rm docker-${DOCKERVERSION}.tgz;' returned a non-zero code: 1
make: *** [Makefile:250: .scope_backend_build.uptodate] Fehler 1
Scope build failed, bailing out
`

Good days and have a nice try to slip in new year.

**Comment by armorvx** [comment]
Hi @all, happy new year...

after I took a little more time to adapt the agent for arm in the new year, I realized that I had a small bug in the go build script ... the agent now runs on the raspberry with kali ... armv7 is not, however right ... GOARCH = arm64.

it was enough to adapt the env just for go build and test the agent extensively.

I have attached a corrected Makefile
many thanks for the support !

[Makefile.txt](https://github.com/deepfence/ThreatMapper/files/7854565/Makefile.txt)

**Comment by sandman137** [comment]
@armorvx That's awesome. Hope you can visualize the raspberry kali node and scan it now!  And thanks for contributing the makefile changes here!
