### ISSUE TITLE
Optimize topology table view

### ISSUE THREAD

**Issue by noboruma** [deepfence/ThreatMapper#1207]
Today topology table view is using the exact same query as topology graph.
One major difference is the connections retrieval, which is only needed for graph view.
Back-end has added a new `SkipConnections` flag in the `TopologyFilters` request that should be set to `true` whenever we request for table view.
This will further optimize table view when we have a high number of nodes and connections.

**Comment by ramanan-ravi** [comment]
<img width="1738" alt="Screenshot 2023-06-07 at 9 08 08 AM" src="https://github.com/deepfence/ThreatMapper/assets/38394463/de50a3d7-f50a-4fd1-8487-8c5c9adaf98e">

I think table view is using `/search/<node_type>` api

**Comment by manV** [comment]
@ramanan-ravi we are using topology api same as graph on cloud view. for all other tables we are using respective /search apis.

**Comment by noboruma** [comment]
Back-end optimized with: https://github.com/deepfence/ThreatMapper/commit/447d108ee43ecd13bc19d81c576d7bdcf0269334
