### ISSUE TITLE
[Threatmapper] Kubernetes Labels are empty 

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#122]
**Describe the bug**
Kubernetes Labels are empty on Kubernetes Agents

**To Reproduce**
1. Go to threatmapper -->topology page
2. Click on any kubernetes pod. The side panel opens up.
3. On the side panel look for the "kubernetes label"
![image](https://user-images.githubusercontent.com/34362153/143993643-b8878555-3c40-4fd3-93e9-a0b3c751223b.png)
4. It is empty.

**Expected behavior**
Kubernetes lables must appear on sidepanel

**Screenshots**

**Components/Services affected**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ramanan-ravi** [comment]
Columns is null in the api response
```
    "tables": [
      {
        "id": "kubernetes_labels_",
        "label": "Kubernetes labels",
        "type": "property-list",
        "columns": null,
        "rows": [
          {
            "id": "label_app",
            "entries": {
              "label": "app",
              "value": "echoserver"
            }
          },
          {
            "id": "label_pod-template-hash",
            "entries": {
              "label": "pod-template-hash",
              "value": "7fc9488fc8"
            }
          }
        ]
      }
    ],
```
