### ISSUE TITLE
[v2] Image and resources are different

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1257]
**Describe the bug**
Image and resources are different, in side panel for a selected scan 

**Expected behavior**
Resources should be a list of all the affected resources from the CVE

![image_720](https://github.com/deepfence/ThreatMapper/assets/22050509/a65b628e-e9b3-4d48-bfaf-6fcc9e6a3e9d)

**Comment by manV** [comment]
@milan-deepfence We need to use the lookup apis for details panel instead of search apis now

**Comment by manV** [comment]
Frontend changes are at https://github.com/deepfence/ThreatMapper/pull/1289
