### ISSUE TITLE
[v2] GCP cloud scanner unable to get cloud resources

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1326]
Cloud scanner is unable to query for resources from GCP 

1. Deploy single account GCP cloud scanner using terrafrom
2. Run Cloud Compliance Scan, scan completes but the cloud resources are not shown 

**Expected behavior**
Show the cloud resources 

**Logs**
[downloaded-logs-20230717-151330.zip](https://github.com/deepfence/ThreatMapper/files/12067959/downloaded-logs-20230717-151330.zip)

**Comment by saurabh2253** [comment]
Steampipe table is taking time to initialise hence the error in logs. My observation is the cloud scanner comes up in some time and the resources are populated. Can you please confirm on your end @gnmahanth

**Comment by shyam-dev** [comment]
If steampipe table takes time to initialize, who is pushing out the error
messages in the logs ? If our task is doing it, can we have a way to detect
steampipe latency before we send out the error messages in the logs ?
