### ISSUE TITLE
[v2] Bulk Select and Start Posture scan on Linux doesn't show option to disable checks

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1327]
**Describe the bug**
selecting and starting scan on multiple node from posture page for Linux doesn't give option to disable controls, options are shown for starting scans on single node

**To Reproduce**
1. Select multiple nodes using check box in the linux posture page
2. Click on start scan
3. Side panel doenot show options to disable controls

**Expected behavior**
Show the controls which were shown while starting scan on single node 

**Screenshots**
when multiple nodes are selected 
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/1e6b9220-dfa2-4be6-892a-b5dc116ab23d)

when single node is selected 
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/b3290e26-7c21-4fe2-87cb-bc70ed896a13)

**Comment by gnmahanth** [comment]
Same issue in topology page 
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/10fd605b-33d7-42cf-b382-880ed158aad5)

**Comment by manV** [comment]
I think that is how we designed it to be?

The control selection is going to be at node level I believe. 

cc @saurabh2253

**Comment by shyam-dev** [comment]
Yes this is expected behavior. This should be the behavior across all types of posture scans that are done in bulk

**Comment by gnmahanth** [comment]
this is whats shown for bulk vulnerability scan, shouldnt the behaviour be same across all type of scans ?

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/bb9472b1-ea26-4881-b4a0-e7b60b2029b9)
