### ISSUE TITLE
[v2] Posture summary counts are worng

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1328]
**Describe the bug**
Scan count is 2 but UI shows resource count as 2

**Screenshots**
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/f1bbd90d-9523-4c9d-914f-3e209b726606)

**Comment by gnmahanth** [comment]
linux counts are worng

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/0720bf18-0e8c-4600-81ee-cd05619a5f11)

**Comment by manV** [comment]
@milan-deepfence resource and scan counts values might be swapped. also take a look at the alignment issues(Maybe this screen is zoomed or browser default font size is modified in the screenshot).
