### ISSUE TITLE
[v2] Kubernetes clusters donot appear under the cloud region in topology graph

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1334]
**Describe the bug**
Kubernetes clusters donot appear under the cloud region in topology graph

**To Reproduce**
1. Connect a kubernetes cluster to the console on any cloud 

**Expected behavior**
kubernetes clusters like other cloud resource should appear under the region they are running 

**Screenshots**
on digital ocean 
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/8182c547-d213-4638-b2fd-ef322d767d4c)

on gcp 
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/79221ab5-453c-44ae-97b8-667f27529e66)

**Comment by saurabh2253** [comment]
This will be difficult to map on graph if a cluster is made up of hosts in multiple regions, hence we have clusters without region

**Comment by noboruma** [comment]
On top of what Saurabh mentioned, we took a decision long time ago to have k8s under `cloud_providers`, not cloud_region - effectively k8s nodes replace cloud provider nodes under topology.
