### ISSUE TITLE
[v2] Base OS vulnerabilities not scanned in vulnerability scan

### ISSUE THREAD

**Issue by jatin-baweja** [deepfence/ThreatMapper#1336]
**Describe the bug**
Base OS packages are not scanned when initiating vulnerability scan.

**To Reproduce**
1. Go to 'Topology'
2. Click on 'Hosts' tab and click on any host in the list
3. Click on Scan dropdown on the top right of the sidebar and select 'Start Vulnerability Scan'
4. In the new pop-up in the sidebar, no information/checkbox to indicate that base OS vulnerabilities will be scanned.
5. Once scan is complete, no OS vulnerabilties

**Expected behavior**
Base OS vulnerabilities also need to be scanned for, other than language vulnerabilities

**Screenshots**
![base_vulnerabilities_checkbox_missing](https://github.com/deepfence/ThreatMapper/assets/4747605/6b16f539-8a74-4d5f-a692-e71e6307c5aa)

**Components/Services affected**

- [x] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by manV** [comment]
@jatin-baweja Please elaborate on the changes you want us to make.

**Comment by jatin-baweja** [comment]
@manV Need to add additional `{"language": "base"}` in `scan_config` array in start vulnerability scan request and a disabled checkbox in the UI saying `OS Packages` like we had earlier
