### ISSUE TITLE
[v2] Download and delete scan button are active for running scans

### ISSUE THREAD

**Issue by jatin-baweja** [deepfence/ThreatMapper#1338]
**Describe the bug**
Download and delete scan button are active for running scans. Also, active scan deletion causes 500 status page to show up

**To Reproduce**
1. Start a vulnerability scan on any host/image
2. Go to 'Vulnerabilities' section and click on 'View all Scans'
3. Click on the latest running scan that was just started
4. Click on the download button to download the xlsx report. Then, click on the delete button while the scan is still running. 500 page should show up.

**Expected behavior**
Active scans should either not be downloadable/deletable or the error on deletion should be shown and download should give a warning that active scans might give 0 results.

**Screenshots**
![Active_scan_download_and_delete_buttons](https://github.com/deepfence/ThreatMapper/assets/4747605/d072f59a-e7cb-4569-a808-8f6b7d7b40ad)

**Components/Services affected**

- [x] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by milan-deepfence** [comment]
This is fixed in: https://github.com/deepfence/ThreatMapper/pull/1325
