### ISSUE TITLE
[v2] Unable to start scan on host from vulnerabilities section

### ISSUE THREAD

**Issue by jatin-baweja** [deepfence/ThreatMapper#1340]
**Describe the bug**
Start Scan button is disabled for active agent in vulnerabilities section.

**To Reproduce**
1. Go to 'Vulnerabilities' section
2. Click on 'View All Scans'.
3. Click on the triple-dot menu next to one of the host/container/image where scan has already been run.
4. In the menu, 'Start Scan' button is disabled.

**Expected behavior**
Start Scan button should be enabled for active host/container/image.

**Screenshots**
![inactive_start_button](https://github.com/deepfence/ThreatMapper/assets/4747605/da4970c2-3d0e-4179-ade3-19a31f8b2073)

**Components/Services affected**

- [x] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by manV** [comment]
We need to enable starting scan from the scans list page as well as scan results page, we just haven't got around it yet.

Before starting scan we need to have a bunch of checks, like if a scan is already running and if the agent is connected to this resource or not(which is easy host type but not sure about container and container_image).

**Comment by shyam-dev** [comment]
All the checks should ideally be done in the backend. The UI should pass the message and get the appropriate status from the backend. @manV  - Raise issues for scan results page and scans list page.

**Comment by gnmahanth** [comment]
its enabled in the UI now
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/e0e0be04-fcb6-4e41-a414-ab0c17fe0373)
