### ISSUE TITLE
[v2] Deleting vulnerability result makes Top vulnerabilities and Top Attack paths disappear, and information in results is removed

### ISSUE THREAD

**Issue by jatin-baweja** [deepfence/ThreatMapper#1344]
**Describe the bug**
Once vulnerability result is deleted, 'Top 5 vulnerabilities' list disappears and 'Top Attack Paths' graph has overlapping text of 'No attack paths found'. Also, results lose information like CVSS score, Description, etc.

**To Reproduce**
1. Go to 'Vulnerabilities' section
2. Click on 'See All Scans'
3. Click on any of the host/container/image to show its latest complete scan details
4. Delete any result from the list. 'Top 5 vulnerabilities' list disappears and 'Top Attack Paths' graph has overlapping text of 'No attack paths found'. Also, other results lose information

**Expected behavior**
On vulnerability result deletion, other results should not be impacted.

**Screenshots**
Before deletion:
![pre_deletion_graphs](https://github.com/deepfence/ThreatMapper/assets/4747605/d620d8dd-f9fa-4cd3-86e7-0effd8d70e43)
![pre_deletion_results](https://github.com/deepfence/ThreatMapper/assets/4747605/7fe998b5-c9b1-4d18-80ef-db6cef9adb1b)

After deletion:
![after_deletion_graphs](https://github.com/deepfence/ThreatMapper/assets/4747605/0d315dd0-fcb5-40ef-a84e-277876c30f42)
![after_deletion_results](https://github.com/deepfence/ThreatMapper/assets/4747605/30bc573c-b580-464f-a662-6203d92d64c7)

**Components/Services affected**

- [x] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by manV** [comment]
Notice all cvss score becomes 0. That's why top vulnerabilities doesn't load.

**Comment by manV** [comment]
Attack path needs to be fixed though

**Comment by gnmahanth** [comment]
Removing this part of code on server fixes the issue
https://github.com/deepfence/ThreatMapper/blob/v2/deepfence_server/reporters/scan/scan_result_actions.go#L138-L153
