### ISSUE TITLE
[v2] Posture Summary cards data is not aligned properly 

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1346]
**Describe the bug**
The counts are not aligned to the labels in posture summary cards 

**Screenshots**
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/f2c09f48-2610-4309-a5b3-147fee945dbe)

**Comment by manV** [comment]
@gnmahanth do you have any customization on your browser like zoom or default font size changed at system/browser level. I see other things also having unusual font size/spacing on your screen.

**Comment by shyam-dev** [comment]
@gnmahanth - Are you in a scenario with custom settings for font sizes ? and screen size ??

**Comment by gnmahanth** [comment]
I think I have font set to Large

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/fefd0995-07c6-4573-aeed-4b5023007d10)

**Comment by manV** [comment]
That must be it. I think you must be seeing other issues with alignment as well across other apps to. I recommend using page zoom instead of font size.

**Comment by shyam-dev** [comment]
@gnmahanth  - Do check with the recommended font options. @manV - Shouldn't this be covered as a part of responsive design ??

**Comment by manV** [comment]
I can check, but it might be too much work for a handful of users doing it. @shyam-dev

**Comment by manV** [comment]
By responsive design we mean the app adapts do different screen dimensions.

**Comment by gnmahanth** [comment]
> @gnmahanth - Do check with the recommended font options. @manV - Shouldn't this be covered as a part of responsive design ??

with Recommended settings its fine, I use Browser level settings as I don't have to override every website 
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/e0d7eecf-23d4-428e-8463-e82fbcc4425e)

**Comment by manV** [comment]
@gnmahanth there is a browser level "Page zoom" setting too.

**Comment by manV** [comment]
@shyam-dev 

Options:
1. We ignore the font-size setting that user has set, less work for us but we are not respecting users choice.
2. We work to adapt to this settings override. More work for us. Not sure if it is worth it since not a lot of people change this setting as browser level.
3. We keep it as it is, some layout issues will be there for the users who has this override set, but it will work functionally.

**Comment by shyam-dev** [comment]
Let's go with 3 for now. Closing this issue.
