### ISSUE TITLE
[v2] pdf reports formatting issues

### ISSUE THREAD

**Issue by manV** [deepfence/ThreatMapper#1351]
**Describe the bug**
See the screenshot

**To Reproduce**
1. Download any pdf report
2. See the issues

**Screenshots**
![image](https://github.com/deepfence/ThreatMapper/assets/4988376/7cc605fe-d6c0-44ee-bfa2-0d6686111e02)

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by gnmahanth** [comment]
Fixed in https://github.com/deepfence/ThreatMapper/pull/1408
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/ca5d09c0-2079-4512-afb2-7e2247064a35)
