### ISSUE TITLE
[v2] Integrations Docs ScreenShots needs update

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1352]
**Describe the bug**
Update documentation Screenshots for integrations docs 
https://github.com/deepfence/ThreatMapper/blob/v2/docs/docs/integrations/index.md

**Comment by varunsharma0286** [comment]
- [ ] PagerDuty: 
The documentation to add the PagerDuty integration is not updated as per the latest PagerDuty UI.
