### ISSUE TITLE
[V2] SBOM presence with no cveid

### ISSUE THREAD

**Issue by milan-deepfence** [deepfence/ThreatMapper#1359]
**Describe the bug**
There are some top cve without cveids

**To Reproduce**
1. Go to Vulnerability module
2. Click on Runtime bom
3. Click on a node from a table row
4. A details info opens on side panel
5. Move through pages and you will empty top cves

**Expected behavior**
There should not be any top cve without cveids and severity

**Screenshots**
<img width="956" alt="Screenshot 2023-07-18 at 5 37 54 PM" src="https://github.com/deepfence/ThreatMapper/assets/111341101/ed63a833-a156-4b65-bc85-bd3b925fef95">

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by gnmahanth** [comment]
in runtime sbom we show all the packages installed on the system even if they donot have any cve's
