### ISSUE TITLE
[v2] Posture filter for scan status not woking

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1365]
**Describe the bug**
apply status filter for posture scans, scans disappear

**To Reproduce**
1. Go to Posture->AWS
2. Run a scan, wait for It to complete
3. Click on filters
4. Select `Posture Scan Status` and select `completed`
5. All scans disappear

**Expected behavior**
Show the list of completed scans 

**Screenshots**
No filters applied
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/65a5e9b8-1f1e-48a8-8975-5f186a566275)

`completed` status selected
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/81dc1fea-a655-4fea-8d60-897093c9f21e)

**Comment by saurabh2253** [comment]
@milan-deepfence Can you please change the filter key to `last_scan_status` and use empty string "" to fetch never scanned accounts
`"contains_filter":{"filter_in":{"cloud_provider":["aws"],"last_scan_status":["COMPLETE"]}` for complete
`"contains_filter":{"filter_in":{"cloud_provider":["aws"],"last_scan_status":[""]}` for never scanned
