### ISSUE TITLE
[V2] Integration report listing need default sorting

### ISSUE THREAD

**Issue by milan-deepfence** [deepfence/ThreatMapper#1366]
**Describe the bug**
Report generation using create report does not appear in order manner.

**To Reproduce**
1. Go to Integration create report
2. Generate a new report
3. Observe new entry in table
4. The newly created report appears at random manner.

**Expected behavior**
Either sort by created at or duration column. Listing api should support sorting

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by milan-deepfence** [comment]
We did UI sorting for now: 
https://github.com/deepfence/ThreatMapper/pull/1379/files#diff-14f8a387803e2045aedaddaac3ed071e4263a97cf3c8d27ead74f525e988abd3

**Comment by gnmahanth** [comment]
@milan-deepfence backend sends sorted response fixed in PR https://github.com/deepfence/ThreatMapper/issues/1366
