### ISSUE TITLE
[v2] Container Report Download Empty Results

### ISSUE THREAD

**Issue by saurabh2253** [deepfence/ThreatMapper#1370]
**Describe the bug**
Downloading vulnerability report from Integrations section for a container using filter gives blank results for pdf/ xlsx download types.

 Check if it has results ready

**To Reproduce**
1. Scan a container for vulnerability.
2. Check if it has results ready
3. Go to integrations sections for report download
4. Set advanced filters for the container scanned

**Expected behavior**
The downloaded report should be populated with results on vuln scan page

**Screenshots**

<img width="1792" alt="Screenshot 2023-07-19 at 8 44 38 AM" src="https://github.com/deepfence/ThreatMapper/assets/3922581/7d8e69fb-6dde-4789-8d30-6d5ff221fb67">
<img width="1792" alt="Screenshot 2023-07-19 at 8 43 56 AM" src="https://github.com/deepfence/ThreatMapper/assets/3922581/8261d56e-650c-4b60-abd6-399301dc4bc8">

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

This is happening because the duration is not a required field on UI and needs an added validation. One can download report 
without setting duration expecting to see all results.

**Comment by jatin-baweja** [comment]
@manV Unable to use the Container filter, container is appearing in API always, but appears in filter intermittently

**Comment by manV** [comment]
@jatin-baweja not sure what you mean by intermittent. Can you post a video or something?

**Comment by jatin-baweja** [comment]
@manV 

https://github.com/deepfence/ThreatMapper/assets/4747605/c4cb670a-07ae-4b3b-9108-cdd4f6cb0f6d

**Comment by manV** [comment]
@jatin-baweja Is this happening on latest code? These issues are fixed I think recently.

**Comment by jatin-baweja** [comment]
@manV Let me rebuild and check
