### ISSUE TITLE
[v2] Advanced Filters in report have container id instead of name - PDF

### ISSUE THREAD

**Issue by saurabh2253** [deepfence/ThreatMapper#1371]
**Describe the bug**
PDF Report contains id of selected container instead of name 

**To Reproduce**
1. Goto download reports under integration
2. Download report for a container

**Expected behavior**
Advanced filter section should container name.

**Screenshots**
<img width="1792" alt="Screenshot 2023-07-19 at 8 44 38 AM" src="https://github.com/deepfence/ThreatMapper/assets/3922581/d626a948-9859-4e95-afcf-052429fa405f">

<img width="827" alt="Screenshot 2023-07-19 at 8 50 50 AM" src="https://github.com/deepfence/ThreatMapper/assets/3922581/d76414ae-35ac-461d-8b5a-5d1304293a1d">

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ramanan-ravi** [comment]
@gnmahanth I think we should only keep 2 or 3 node names in the file name.
If I select 50 nodes and generate report, it will be a issue.

**Comment by gnmahanth** [comment]
closing issue, this is expected
