### ISSUE TITLE
[v2] Options scroll reset on Create Reports page - Integration

### ISSUE THREAD

**Issue by saurabh2253** [deepfence/ThreatMapper#1372]
**Describe the bug**
The Dropdowns get the scroll state reset which makes it a weird UI behaviour.

**To Reproduce**
1.Open advanced filter in Create Report page 

**Expected behavior**
The options should stay still while user is selecting

**Screenshots**

https://github.com/deepfence/ThreatMapper/assets/3922581/62185bfc-025e-4055-b8a8-393ac4afef5b

**Components/Services affected**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by milan-deepfence** [comment]
May be similar issue with: https://github.com/deepfence/ThreatMapper/issues/1348

**Comment by manV** [comment]
it looks like order is changing whenever data is refreshed from the server. @milan-deepfence please double check if that is the case. we might need backend help here.

**Comment by milan-deepfence** [comment]
Yes with order it works
