### ISSUE TITLE
Management Console Topology page does not render correctly on Safari

### ISSUE THREAD

**Issue by ogarrett** [deepfence/ThreatMapper#140]
**Describe the bug**

The top status bar on the topology page is offset down by a number of pixels

Status bar is this div: 
   &lt;div class="header-view expand-fixed-panel"&gt;&lt;div class="infra-summary"&gt; ... &lt;/div&gt;&lt;/div&gt;

Effect is that the status bar obscures the various cloud/host/etc selectors, making the topology view impossible to navigate.

Problem is apparent on Safari (MacOS, iPad, iPhone).  Problem is not present on FireFox or Chrome on MacOS.

**To Reproduce**

On an affected system, go to the topology page

**Expected behavior**

Status bar should be pinned to top of page, as it is on FireFox/Chrome

**Screenshots**

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/3711627/145432569-6110b15d-5841-4576-bc90-61bb80cd2e53.png">

**Components/Services affected**

- [X] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ibreakthecloud** [comment]
fixed
