### ISSUE TITLE
[v2] Slack notification doesnot work when the scan contains more results (>100)

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#1405]
**Describe the bug**
When any scan has results >100 the notification sent is successful but slack doesn't display the notification

**To Reproduce**
1. Configure a slack channel for notification 
2. Run any scan which generates large number of results
3. Slack should receive notification (logs shows notification is sent)

**Expected behavior**
All sent notifications should be visible in slack

**Comment by ramanan-ravi** [comment]
https://api.slack.com/docs/rate-limits
Some of the integrations have rate limits.
We have to send them in batches.
