### ISSUE TITLE
Cloud Scanner not fetching resources when there is a permissions issue for one of the resource

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#1427]
When there are multiple resources and an explicit deny policy or a service control policy denies permission for one or many of those resources, cloud scanner does not fetch resources in this case, instead of ignoring the denied ones and fetching others

```
Error: operation error EKS: ListClusters, https response error StatusCode: 403, api error AccessDeniedException: User: arn:aws:sts::1234567890:assumed-role/deepfence-cloud-scanner-task-role/aaaa is not authorized to perform: eks:ListClusters on resource: arn:aws:eks:us-east-1:1234567890:cluster/" with an explicit deny
```

**Comment by RRcwhiting** [comment]
what release fixed this?

**Comment by ramanan-ravi** [comment]
> what release fixed this?

Hello @RRcwhiting, the fix is in this image `quay.io/deepfenceio/cloud-scanner:1.5.0`.
You can deploy cloud scanner by following this: https://docs.deepfence.io/threatmapper/docs/cloudscanner
