### ISSUE TITLE
[v2] Blank names for containers in filters in report form

### ISSUE THREAD

**Issue by jatin-baweja** [deepfence/ThreatMapper#1438]
**Describe the bug**
Container names are blank in filters dropdown on report form.

**To Reproduce**
1. Go to 'Integrations'
2. Click on 'Create New Report'
3. Select 'Vulnerability' as 'Resource' and 'Container' as 'Node Type'
4. Check the 'Container' select box under 'Advanced Filter'

**Expected behavior**
It should not list checkboxes with blank names.

**Screenshots**
![blank_container_filter_checkboxes](https://github.com/deepfence/ThreatMapper/assets/4747605/6ddb6ddb-29fe-4195-894a-6e229b35c93c)

**Components/Services affected**

- [x] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ramanan-ravi** [comment]
This is most probably a backend issue @jatin-baweja. Can you confirm?

**Comment by jatin-baweja** [comment]
> This is most probably a backend issue @jatin-baweja. Can you confirm?

@ramanan-ravi Multiple places where we may require stopped containers in the search. Since at this specific place we do not require so,  we can use a filter



> @jatin-baweja can you outline which filter to use if I need to search container except deleted?

@manV NotContains filter:
```
"not_contains_filter": {
  "filter_in": {
    "docker_container_state": [
      "deleted"
    ]
  }
}
```

**Comment by manV** [comment]
Let's say we run a scan on a container, and then the container get deleted/stopped. but we still want to download report. in this case above filter will filter out deleted container and I will not be able to download report for it.

My question is, shall we allow download report for deleted containers?

Why we empty the name if container is stopped?

@jatin-baweja @ramanan-ravi

**Comment by manV** [comment]
We already have active flag in container search results, how is that different from stopped status?

**Comment by jatin-baweja** [comment]
> Let's say we run a scan on a container, and then the container get deleted/stopped. but we still want to download report. in this case above filter will filter out deleted container and I will not be able to download report for it.
> 
> My question is, shall we allow download report for deleted containers?
> 
> Why we empty the name if container is stopped?


For such cases, the container has been removed from the host. There is a possibility that a new container can be spawned with the same name, but with no similar property(not even the same image). I don't think we can merge the new and old containers with the same name. One thing I can think of is using the digest as the name for deleted containers. But we wouldn't want to show such containers on the UI, as the number of deleted containers might increase over time and make it difficult for the user to select running containers with all the digests from deleted containers mixed with names of running containers. We can have a checkbox as an option to list deleted containers(for users who would want to have deleted containers in the list) and based on that, we can make the call to the containers API with or without the filter. Default for the checkbox would be to not list deleted containers



> We already have active flag in container search results, how is that different from stopped status?

Active flag is different in as it pertains to the running status of the deepfence sensor, versus the stopped status which pertains to container state. A container may still be in running state, but will be inactive if the sensor on the host has been disconnected. I'm not sure if they can be merged, but need to look deeper into any use cases for having both

**Comment by ramanan-ravi** [comment]
@manV Can you fill the containers dropdown with `node_name` instead of `docker_container_name`?
Users can search a container in a certain host.

I am also setting container id in node_name when container name is not there.

**Comment by ramanan-ravi** [comment]
@manV Can you fill the containers dropdown with node_name instead of docker_container_name?
Users can search a container in a certain host.

I am also setting container id in node_name when container name is not there.

**Comment by manV** [comment]
Action items for frontend

1. Use node_name on all drop-downs for display purposes.
2. Double check usage of active flag, on integration advanced filters, consider "include dead nodes" checkbox to filter and populate advanced filter drop-down.


cc. @milan-deepfence

**Comment by milan-deepfence** [comment]
1. Use node_name on all drop-downs for display purposes. Fixed in: https://github.com/deepfence/ThreatMapper/pull/1458

**Comment by milan-deepfence** [comment]
2. Double check usage of active flag, on integration advanced filters, consider "include dead nodes" checkbox to filter and populate advanced filter drop-down. 
Fixed in: https://github.com/deepfence/ThreatMapper/pull/1460
