### ISSUE TITLE
[v2] <none>:<none> names for container images in filters in create new report form

### ISSUE THREAD

**Issue by jatin-baweja** [deepfence/ThreatMapper#1439]
**Describe the bug**
Container Image names with "<none>:<none>" in filters dropdown on report form.

**To Reproduce**
1. Go to 'Integrations'
2. Click on 'Create New Report'
3. Select 'Vulnerability' as 'Resource' and 'ContainerImage' as 'Node Type'
4. Check the 'Container Image' select box under 'Advanced Filter'

**Expected behavior**
Untagged container images should not be ingested into the topology data

**Screenshots**
![none_container_image_filter](https://github.com/deepfence/ThreatMapper/assets/4747605/f265fb12-6f6e-4027-88f5-a9896fa3d17e)

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ramanan-ravi** [comment]
Ya, I think we should skip them in the agent probe itself.
