### ISSUE TITLE
Better Icon for K8s Resources 

### ISSUE THREAD

**Issue by sangam14** [deepfence/ThreatMapper#1444]
![container](https://github.com/deepfence/ThreatMapper/assets/21982562/dd68ea96-d000-4414-8462-812a8a12134f)
![pod](https://github.com/deepfence/ThreatMapper/assets/21982562/c4415891-d5a9-480d-acd0-3cc42d335b03)
![pods](https://github.com/deepfence/ThreatMapper/assets/21982562/d9646b86-9cdb-4f60-a476-71b85dd5a91e)
![container-runtime-interface-container-d](https://github.com/deepfence/ThreatMapper/assets/21982562/a5910e6e-3175-4288-ab36-ae07495ce8a3)
![container-runtime-interface-cri-o](https://github.com/deepfence/ThreatMapper/assets/21982562/2d19f487-0c79-4475-90a6-4bd3b1537830)
![container-runtime](https://github.com/deepfence/ThreatMapper/assets/21982562/b81a2845-122e-4c25-9564-baf13d696fc1)

**Comment by manV** [comment]
@sangam14 can you explain what should happen here?

**Comment by sangam14** [comment]
You will see few icon for following resources good to have some standard identification as per k8s component 
[container]
[pod]
[pods]
[container-runtime-interface-container-d]
[container-runtime-interface-cri-o]

**Comment by manV** [comment]
It doesn't look like it will fit with our theme directly, but if you have vector sources of these icons we can modify it to fit our theme. Please post original source from where you got these icons. Thanks.

**Comment by sangam14** [comment]
https://github.com/ExamProCo/Kubernetes-Architecture-Icons
