### ISSUE TITLE
[V2] Vuln Scans fail for registry image when started from scan result list

### ISSUE THREAD

**Issue by saurabh2253** [deepfence/ThreatMapper#1482]
**Describe the bug**
Vuln Scans fail for registry image when started from scan result list

**To Reproduce**
1. Add a registry
2. Scan any image x
3. Go to Vulnerabilities -> Show All Scans
4. Scan the image x again from the options on scan result row

**Expected behavior**
Scan should go through but fails.

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by manV** [comment]
@saurabh2253 can you please tell us what change needs to be made here?

**Comment by saurabh2253** [comment]
UI is sending node_type:"container_image" instead of "image"

**Comment by manV** [comment]
@saurabh2253 I think this API should hard fail with 400 if wrong node type is passed.
