### ISSUE TITLE
[V2] On registry addition, show loading gif till entries are available

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#1488]
When a registry account is added, show loading gif till the images are fetched in the backend

**Comment by manV** [comment]
We need a `syncing` flag against a registry account object in the api so we can show loaders appropriately. @ramanan-ravi

**Comment by milan-deepfence** [comment]
I saw an issue in image syncing where node id which has @ and . character fails to use api path:
node_id: quay_dev@deepfence.io and failed api is :
<img width="1245" alt="Screenshot 2023-08-31 at 10 53 58 AM" src="https://github.com/deepfence/ThreatMapper/assets/111341101/feb3155b-b0f0-49dc-842d-88f5849f686b">

**Comment by shyam-dev** [comment]
in as much as possible we should use the url encode function when we add parameters to url's

**Comment by ramanan-ravi** [comment]
> I saw an issue in image syncing where node id which has @ and . character fails to use api path: node_id: [quay_dev@deepfence.io](mailto:quay_dev@deepfence.io) and failed api is : <img alt="Screenshot 2023-08-31 at 10 53 58 AM" width="1245" src="https://user-images.githubusercontent.com/111341101/264543079-feb3155b-b0f0-49dc-842d-88f5849f686b.png">

@ibreakthecloud Can you check this?

**Comment by ibreakthecloud** [comment]
![image](https://github.com/deepfence/ThreatMapper/assets/18168330/192c477a-8e1d-46a2-b9a7-9f5ed3e05e59)
![image](https://github.com/deepfence/ThreatMapper/assets/18168330/e53d79e8-8e79-48ea-a055-41355b879d2e)

looks like this @manV

**Comment by ramanan-ravi** [comment]
@ibreakthecloud @milan-deepfence 
Low priority.
This should be added in image list page also
![image](https://github.com/deepfence/ThreatMapper/assets/38394463/568ab565-a264-4003-bd4b-003e071424fc)

**Comment by ibreakthecloud** [comment]
> I saw an issue in image syncing where node id which has @ and . character fails to use api path: node_id: [quay_dev@deepfence.io](mailto:quay_dev@deepfence.io) and failed api is : <img alt="Screenshot 2023-08-31 at 10 53 58 AM" width="1245" src="https://user-images.githubusercontent.com/111341101/264543079-feb3155b-b0f0-49dc-842d-88f5849f686b.png">

@milan-deepfence can you create a new issue out of this. This was not part of 1488 fix
