### ISSUE TITLE
[V2](feat) Show Vulnerabilities comparison between current and last scans

### ISSUE THREAD

**Issue by ibreakthecloud** [deepfence/ThreatMapper#1501]
**Additional context**
Currently we don't show any difference between two vulnerability scan results. An option to compare scan results would be handy to identify following things:

- New packages introduced
- New CVEs detected
- CVEs mitigated

**Describe the solution you'd like**
An option in UI to compare scan report between current and any historical scans
![image](https://github.com/deepfence/ThreatMapper/assets/18168330/adf84d6c-5050-43b8-8444-5e01f39f099f)

**Describe alternatives you've considered**
Exporting the vulnerabilities to XLSX file and processing it. 

**Components/Services**

- [x] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**
At low level, comparision should happen using two `scan_id`s and `node_id` should be same.

**Comment by noboruma** [comment]
@ibreakthecloud to compare scan results, I propose we regroup Vulnerability nodes in two groups: Common & Different groups.
Given sets, A = {Vuln nodes of Scan 1} & B = {Vuln nodes of Scan 2}
- Common group can be computed as: intersect (A, B)
- Different group can be computed as: union(A, B) - insersect(A, B)

Those operations should be fairly simple to do with neo4j queries.

**Comment by ibreakthecloud** [comment]
> @ibreakthecloud to compare scan results, I propose we regroup Vulnerability nodes in two groups: Common & Different groups. Given sets, A = {Vuln nodes of Scan 1} & B = {Vuln nodes of Scan 2}
> 
> * Common group can be computed as: intersect (A, B)
> * Different group can be computed as: union(A, B) - insersect(A, B)
> 
> Those operations should be fairly simple to do with neo4j queries. We can reused the `DETECTED` relationship to fetch the nodes efficiently.

something similar I am doing: https://github.com/deepfence/ThreatMapper/issues/1501

**Comment by ramanan-ravi** [comment]
@manV @milan-deepfence
I think we should let user compare against any tag of same image and not restrict to same tag.

**Scenario:**
User has image `application:1.12`. They scan it and see the vulnerabilities.
Now they upgrade the dependencies and fix some of the issues.
Their CI system might build the changes as `application:1.13`.
User now wants to compare `application:1.13` against `application:1.12` to check if the vulnerabilities actually got fixed.

**Comment by ibreakthecloud** [comment]
@milan-deepfence backend PR is merged to `main`. You can find the apis in swagger ui under [Diff Add](https://167.172.233.137/deepfence/swagger-ui/#/Diff%20Add). 

PR has the way to use it too.

**Comment by milan-deepfence** [comment]
I find spec is breaking in code generation:
Errors: 
[[deepfence-server] ./api-spec.json]    -attribute paths.'/deepfence/diff-add/compliance'(post).operationId is repeated
[[deepfence-server] ./api-spec.json]    -attribute paths.'/deepfence/diff-add/vulnerability'(post).operationId is repeated
[[deepfence-server] ./api-spec.json]    -attribute paths.'/deepfence/diff-add/secret'(post).operationId is repeated
[[deepfence-server] ./api-spec.json]    -attribute paths.'/deepfence/diff-add/malware'(post).operationId is repeated

Will it  be possible to give different operationId for each of scan type, may be secretScanDiff, vulnerabilityScanDiff etc.

**Comment by noboruma** [comment]
Thanks for reporting Milan - this is because we use golang generics and openAPI does not support the syntax yet.
I have submitted a PR to fix that: #1531

**Comment by ramanan-ravi** [comment]
@milan-deepfence @manV This is required for Secrets, Malware and Compliance also

**Comment by manV** [comment]
@milan-deepfence Can this be closed?
