### ISSUE TITLE
ThreatMapper scans don't differentiate between images with same tag

### ISSUE THREAD

**Issue by ogarrett** [deepfence/ThreatMapper#154]
**Describe the bug**

I have two xwiki-based images running on my K8s cluster:

`owen-xwiki-7f9776d8fd-mpf8w                               1/1     Running   0          17h
xwiki-694f6c4cd9-4pmlp                                    1/1     Running   0          2d18h`

xwiki is the 'official' dockerhub xwiki:stable image: `kubectl create deployment xwiki --image=xwiki:stable` and is running on node -zb
owen-xwiki is a private build from oweng/xwiki: `kubectl create deployment owen-xwiki --image=oweng/xwiki:stable` and is running on node -qh

Note that the fully-qualified name for the official image is 'library/xwiki:stable'.

The ThreatMapper MC sometimes confuses the two:

- I start a manual scan on xwiki:stable.  While it is running, I cannot start a scan on oweng/xwiki:stable ('vulnerability scan is already running')
- In the topology view (graph and table), the metadata for the xwiki container can be incorrect, for example, the oweng/xwiki:stable container can be identified as the library/xwiki:stable one (or the other way round...)

Note that the two images are correctly distinguished in other parts of the MC; for example, the Vulnerability Scans list separates scans for library/xwiki:stable and oweng/xwiki:stable

**Expected behavior**

Accurate and consistent identification of images with the same name:tag, but sourced from different repositories.

**Components/Services affected**

- [X] UI/Frontend
- [X] API/Backend
- [X] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ramanan-ravi** [comment]
@ogarrett If the image id is same for multiple images (image created using `docker tag`), they are considered one and same by scope, so starting scan on one will reflect in the other one.
