### ISSUE TITLE
[V2] Priority scans

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#1592]
- Option to run a vulnerability / secret / malware / compliance scan on priority
- If 15 container scans / 1000 registry image scans are scheduled and if the user wants to start one container scan on priority (run this before other scheduled scans), it should be supported

**Comment by noboruma** [comment]
We need to add priority fields across all our controls.
We can use 0-255, 0 being high priority and 255 lowest priority. 
That should give us enough room for future features.

Then when we construct the list of controls/actions for worker/agent, we can sort by that field. We should do that directly inside our neo4j queries where we retrieve actions.
Note that there is already an order based on the type of controls, we need to double check this order still makes sense or if all controls need to be treated equal.

This should require little changes and everything should be doable via neo4j (no asynq involvement). Start scan request might need some new priority fields.
