### ISSUE TITLE
Error when trying to update the helm

### ISSUE THREAD

**Issue by thelubomir** [deepfence/ThreatMapper#1618]
When I try to update the helm chart  deepfence-console from version 1.5.0 to 2.0.0 got the error:
`helm upgrade deepfence-console -f tm-values.yaml deepfence/deepfence-console --version 2.0.0 --force
Error: UPGRADE FAILED: failed to replace object: Deployment.apps "deepfence-router" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"deepfence-console", "app.kubernetes.io/name":"deepfence-console", "component":"router", "name":"deepfence-router"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && failed to replace object: Deployment.apps "deepfence-ui" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"deepfence-console", "app.kubernetes.io/name":"deepfence-console", "component":"ui", "name":"deepfence-ui"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && failed to replace object: StatefulSet.apps "deepfence-kafka-broker" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden`
But deepfence-router updated normally. What should I do?

**Comment by gnmahanth** [comment]
Hi @thelubomir we currently do not support upgrade from version `1.5.0` to `2.0.0`, please follow the steps mentioned in the docs to install version `2.0.0`, Note that you will also need to update the agents to work with new version

installation docs: https://docs.deepfence.io/threatmapper/docs/installation

**Comment by thelubomir** [comment]
Oh.. I see, thank you for info.
