### ISSUE TITLE
(feature) Filters in scan results page

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#1621]
Add more filters in scan results page:
- CVE ID
- Attack vector
- Package
- CVE type (Language) (Was missing, fixed in https://github.com/deepfence/ThreatMapper/pull/1623)

Similarly for other scans

![Vulnerability-Scan-Results-Deepfence](https://github.com/deepfence/ThreatMapper/assets/38394463/4a7200f6-6310-48b6-ba4e-30cfa1eaa8e7)

**Comment by shyam-dev** [comment]
Filter by Language is another good to have item

**Comment by milan-deepfence** [comment]
@shyam-dev @ramanan-ravi @ibreakthecloud  
What filters do we want to add for Malware and Secret?

Result page for Malware scan:
<img width="1651" alt="Screenshot 2023-10-05 at 5 49 09 PM" src="https://github.com/deepfence/ThreatMapper/assets/111341101/b76d29ed-fa38-463d-af41-687b03a04f3f">

Result page for Secret scan:
<img width="1665" alt="Screenshot 2023-10-05 at 5 49 30 PM" src="https://github.com/deepfence/ThreatMapper/assets/111341101/511b5343-3322-41d7-ac59-92cbd2558f79">

**Comment by ramanan-ravi** [comment]
@milan-deepfence 

Nothing in Secret and Malware scans.

In posture scan, we should add *ID*

![image](https://github.com/deepfence/ThreatMapper/assets/38394463/9a25f440-cf0b-41db-9526-7d1d1c67b160)

**Comment by milan-deepfence** [comment]
Need api to get id list with pagination support similar to cveid.

**Comment by ramanan-ravi** [comment]
> Need api to get id list with pagination support similar to cveid.

@ibreakthecloud Is completion api available for posture results?

**Comment by ibreakthecloud** [comment]
ref: https://github.com/deepfence/ThreatMapper/pull/1953

**Comment by ibreakthecloud** [comment]
@milan-deepfence I added the completion api for `compliance` and `cloud-compliance` . You can add filters in posture now.
