### ISSUE TITLE
[Registries] Image and total tags filter on docker registry not functional

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#164]
**Describe the bug**

**To Reproduce**
1. Go to https://xxx.xx.xx.xx/#/registry_vulnerability_scan/docker_hub
2. Click on the 3 dots on the top right of any repo
![image](https://user-images.githubusercontent.com/34362153/146801306-88516bf6-a60a-49b0-8ebd-1cae165b9faf.png)

3. You will see Image and Total images, they are not clickable.

**Screenshots**

**Components/Services affected**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by manV** [comment]
On the table, we disallow hiding the last two columns. Since this table only has two columns, you cannot hide any columns anymore. We will remove column selection from this table. @jo19in1

**Comment by jo19in1** [comment]
> On the table, we disallow hiding the last two columns. Since this table only has two columns, you cannot hide any columns anymore. We will remove column selection from this table. @jo19in1

Noted

**Comment by manV** [comment]
We have removed column selection on this table with https://github.com/deepfence/ThreatMapper/pull/162
