### ISSUE TITLE
Page redirection for new console and new user

### ISSUE THREAD

**Issue by milan-deepfence** [deepfence/ThreatMapper#1650]
**Describe the bug**
User should be redirected to onboard page when a new console is created and login with new user.

**To Reproduce**
1. Create a new console
2. Register a new user
3. Login with this new user
4. User is directly landed to dashboard page

**Expected behavior**
User should be redirected to onboard page not dashboard for this very first user.

**Components/Services affected**

- [X] UI/Frontend
- [X] API/Backend

**Comment by ramanan-ravi** [comment]
Fixed in https://github.com/deepfence/ThreatMapper/commit/7f22989f66179dea2db8d36afac3625bf97b6f5a#diff-be209e72a7f131a25edd3ec27920762850594b334fbc75bdbc7daceb9a17606bR82-R86
