### ISSUE TITLE
[Registries] adding large registries -->need to show a loader 

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#167]
**Describe the bug**

**To Reproduce**
1. Go to https://xxx.xxx.xx.xx/#/registry_vulnerability_scan/docker_hub
2. Add a large docker registry such as the one below
https://hub.docker.com/r/ibmcom/log4j-jsonevent-layout-ppc64le

![image](https://user-images.githubusercontent.com/34362153/146909443-5c39b2d0-19cb-442e-9d2f-331156da7361.png)

3. Now click on Save Credentials
4. Once you save the creds, you will get a loader
![image](https://user-images.githubusercontent.com/34362153/146909902-bccbce56-b876-4ded-a34d-43d987b40013.png)

5. CLose this modal

![image](https://user-images.githubusercontent.com/34362153/146910005-5c4a9cfc-9cd6-4d47-9692-84c168222810.png)

6. You will now see an empty row message
7. But infact console is pulling all the images for the scan. Hence there must a loader modal till all images are pulled and show.
![image](https://user-images.githubusercontent.com/34362153/146910236-87cbcfb8-1374-4738-96d4-ae19e3026fda.png)

**Expected behavior**

Need a loader icon to be show when registries are being pulled

**Screenshots**

**Components/Services affected**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by manV** [comment]
We can add flag that says that registry is being added in the list response, so we can show the status in the ui instead of "no rows found" message. @ramanan-ravi ?

**Comment by ramanan-ravi** [comment]
> We can add flag that says that registry is being added in the list response, so we can show the status in the ui instead of "no rows found" message. @ramanan-ravi ?

Sure, that works.

**Comment by ramanan-ravi** [comment]
@manV Added new field `registry_update_in_progress` (boolean)

- Response when registry update is in progress
```
{
  "data": {
    "data": [
      
    ],
    "last_updated": "2021-12-21T17:13:01.771889Z",
    "registry_update_in_progress": true,
    "scan_in_progress": 0,
    "total": 0,
    "total_scanned": 0,
    "unique_images": 0
  },
  "error": null,
  "success": true
}
```

- Response when registry update is finished
```
{
  "data": {
    "data": [
      {
        "image_name": "deepfenceio/deepfence_fetcher_ce",
        "tags": [
          {
            "docker_image_size": "182.22 MB",
            "id": "3de386d8c211e83b77cff08140fa4171",
            "image_name": "deepfenceio/deepfence_fetcher_ce",
            "image_name_with_tag": "deepfenceio/deepfence_fetcher_ce:latest",
            "image_os": "linux",
            "image_tag": "latest",
            "pushed_at": "2021-12-20T16:51:07.649242Z",
            "scope_id": "deepfenceio/deepfence_fetcher_ce:latest;<container_image>",
            "type": "registry_image",
            "vulnerability_scan_status": "never_scanned",
            "vulnerability_scan_status_msg": "",
            "vulnerability_scan_status_time": ""
          }
        ],
        "total_tags": 1,
        "type": "registry_image"
      }
    ],
    "last_updated": "2021-12-21T17:13:06.550076Z",
    "registry_update_in_progress": false,
    "scan_in_progress": 0,
    "total": 1,
    "total_scanned": 0,
    "unique_images": 1
  },
  "error": null,
  "success": true
}
```
