### ISSUE TITLE
Diagnostic logs message field is not user friendly

### ISSUE THREAD

**Issue by ibreakthecloud** [deepfence/ThreatMapper#1679]
**Describe the bug**
Message field doesnot make any sense for an user

**Screenshots**
![image](https://github.com/deepfence/ThreatMapper/assets/18168330/7ac35cb6-9558-49f8-937e-47beeccd7f38)

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ramanan-ravi** [comment]
@ibreakthecloud [This](https://github.com/deepfence/ThreatMapper/blob/main/deepfence_utils/utils/structs.go#L8-L18) probably needs to be changed since we now use SeaweedFS
