### ISSUE TITLE
helm install fails on EKS

### ISSUE THREAD

**Issue by AbubakrSamsodien** [deepfence/ThreatMapper#1696]
**Describe the bug**
trying to install threatmapper v2 on EKS with terraform

but i get this error from my terraform output:
```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in Secret.stringData.AWS_ACCESS_KE
Y, unknown object type "nil" in Secret.stringData.AWS_SECRET_KEY, unknown object type "nil" in Secret.stringData.DF_S3_BUCKET_NAME]
│ 
│   with helm_release.deepfence-console[0],
│   on helm_releases.tf line 54, in resource "helm_release" "deepfence-console":
│   54: resource "helm_release" "deepfence-console" {
```
this is my tf resource. based off [ref](https://community.deepfence.io/threatmapper/docs/console/kubernetes#install-the-threatmapper-management-console):
```
resource "helm_release" "deepfence-console" {
  count      = var.threatmapper_enabled == true ? 1 : 0
  name       = "deepfence-console"
  namespace  = kubernetes_namespace.operations-namespace.id
  repository = "https://deepfence-helm-charts.s3.amazonaws.com/threatmapper"
  chart      = "deepfence-console"
  version    = "2.0.1"
  set {
    name  = "global.imageTag"
    value = "2.0.0"
  }
  set {
    name  = "global.storageClass"
    value = "gp3"
  }
}
```

my versions:
- eks 1.24
- terraform 1.4.6
  - helm provider 2.5.1

**Comment by gnmahanth** [comment]
Hi @AbubakrSamsodien, Thanks for reporting the issue.

I am able to reproduce the above error with `helm_provider v2.5.1`

I am not seeing the above error with latest version of helm provider, please update the helm provider to latest version and try again

verified on  `helm_provider v2.11.0` there are no errors.

**Comment by AbubakrSamsodien** [comment]
unfortunately i still get the same issue when using ```helm_provider to v2.11.0```.
i even tried updating terraform to ```1.6.2``` and updated the deepfence-console chart to ```2.0.2``` and the image tag to ```2.0.1```

but no luck :(

**Comment by gnmahanth** [comment]
@AbubakrSamsodien we have update the helm chart to remove unused secrets, the version `2.0.2`  remains same for the chart can you try again using `helm_provider to v2.11.0`

**Comment by AbubakrSamsodien** [comment]
aaah works now :)
