### ISSUE TITLE
Integrations are not displayed

### ISSUE THREAD

**Issue by ApoorvMangal** [deepfence/ThreatMapper#1712]
The integrations are not being displayed to be configured.

Thanks,
Apoorv

![image](https://github.com/deepfence/ThreatMapper/assets/64570087/8694a894-4435-496c-bae8-60cf2fd7a45a)
![image](https://github.com/deepfence/ThreatMapper/assets/64570087/baa193f1-3509-4fa2-856c-3b011d0f4af4)

**Comment by ibreakthecloud** [comment]
@ApoorvMangal what is the image tag you are using or is it custom built from source code?

**Comment by ApoorvMangal** [comment]
@ibreakthecloud 2.0.1. 
Built from latest master now and it is working.

**Comment by ApoorvMangal** [comment]
@ibreakthecloud apart from this topic, would like to know where the cspm data resides.

I am testing its integration with OpenProject instead of JIRA and would like to understand where the CSPM data is stored and is there any API to generate reports for cloud compliance?

**Comment by ramanan-ravi** [comment]
@ApoorvMangal CSPM data is stored in neo4j.
Please check these apis:
- https://CONSOLE_URL/deepfence/swagger-ui/#/Cloud%20Scanner/listCloudComplianceScan
- https://CONSOLE_URL/deepfence/swagger-ui/#/Cloud%20Scanner/resultsCloudComplianceScan

**Comment by ApoorvMangal** [comment]
@ramanan-ravi do you have any documentation on using these API's?

Say I want to extract cloud compliance data for an aws account 1234, how can I use this?

**Comment by varunsharma0286** [comment]
@ApoorvMangal You can check the swagger ui for the api reference:
* https://CONSOLE_URL/deepfence/swagger-ui/#/
This will have the request format, sample request json and valid api responses. 

For instance, for getting the cloud compliance data for an account id `AWS_ACCOUNT`, below would be the steps:
* Step1: Get the nodeid for the account `AWS_ACCOUNT` using the cloud-node list api: `/deepfence/cloud-node/list/accounts`
* Step2: Get the scanid for this account by using the scan list api: `/deepfence/scan/list/cloud-compliance` 
* Step3: Get the results by using this scan id in the results api `/deepfence/scan/results/cloud-compliance`
