### ISSUE TITLE
Cloud Compliance reports are blank

### ISSUE THREAD

**Issue by ApoorvMangal** [deepfence/ThreatMapper#1713]
On downloading the cloud compliance report it just returns an excel/pdf with header.

Thanks,
Apoorv

<img width="640" alt="Screenshot 2023-11-03 at 14 45 10" src="https://github.com/deepfence/ThreatMapper/assets/64570087/19fb7791-44c0-4fc7-8609-fce25e7172bf">
[cloud_compliance_aws_895d39c7-61d0-42fa-9bc9-86843c277aa6.pdf](https://github.com/deepfence/ThreatMapper/files/13248501/cloud_compliance_aws_895d39c7-61d0-42fa-9bc9-86843c277aa6.pdf)
[cloud_compliance_aws_47fbb477-c522-4d9b-8ebc-cf779f740984.xlsx](https://github.com/deepfence/ThreatMapper/files/13248502/cloud_compliance_aws_47fbb477-c522-4d9b-8ebc-cf779f740984.xlsx)

**Comment by shyam-dev** [comment]
This is being tracked here https://github.com/deepfence/ThreatMapper/issues/1744

**Comment by ramanan-ravi** [comment]
Available in v2.1.0: https://docs.deepfence.io/threatmapper/docs/v2.1/installation
