### ISSUE TITLE
DOCKER DESKTOP PULL REQUEST

### ISSUE THREAD

**Issue by lumideez** [deepfence/ThreatMapper#1726]
I used the following command on my Windows in order to install a container for the ThreatMapper in my Docker desktop

**docker pull https://github.com/deepfence/ThreatMapper/raw/release-2.0/deployment-scripts/docker-compose.yml**

It didnt work

also wget doesnt work.

Please help

**Comment by noboruma** [comment]
Hello @lumideez, thanks for reaching out.
We don't support Windows console at the moment, we invite you to use GNU/Linux if possible.

**Comment by lumideez** [comment]
but I'm running it through Docker desktop. Do you mean I wont be able to access the console?

**Comment by noboruma** [comment]
Can you please describe your entire setup?
The recommended way to use ThreatMapper is to host the console on a linux system (ARM64 or AMD64) and have agents deployed on linux systems or kubernetes.
As of today, we do not support windows, as in for agents they rely on linux kernel features while the console might work but we don't support nor recommend it.

**Comment by lumideez** [comment]
my entire setup runs through docker desktop on windows. I thought I could setup the Threatmapper as a container inside my docker and using CMD I could run the command line (which ran successfuly) but I couldnt access the console afterwards. If I host on my Linux which i can access through SSH can I see the GUI on my Windows browser on another computer on the same local network using the static IP of my Linux?

**Comment by shyam-dev** [comment]
Hello @lumideez  -- Yes, if you have a linux host, you can install the ThreatMapper platform in that host, and use your windows system to open a browser and connect to that linux host to view the GUI of ThreatMapper platform.
