### ISSUE TITLE
[Registries] Refresh button animation

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#174]
**Describe the bug**

**To Reproduce**
1. Go to Registries-->ECR Registries
2. The refresh button on top of the table, can we have an animation for the same? It will help the user to know that there is some action is happening when user clicks that button
![image](https://user-images.githubusercontent.com/34362153/147038602-be78f1f0-0f4b-4699-8aa0-ce51b6055b63.png)

3.The "i" button on left does nothing. 

**Expected behavior**

**Screenshots**

**Components/Services affected**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ramanan-ravi** [comment]
@manV @saiprasanth1303 On click of a refresh button, create a notification message "Registry images will be refreshed soon"
