### ISSUE TITLE
Comparison between two cloud posture scans is incorrect

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#1746]
Here are 2 scan results for the same AWS account (All benchmarks selected)

```
"severity_counts": {
    "alarm": 6371,
    "info": 107,
    "ok": 14680,
    "skip": 24
},

 "severity_counts": {
    "alarm": 6339,
    "info": 107,
    "ok": 12616,
    "skip": 24
},
```

But comparison is empty

![image](https://github.com/deepfence/ThreatMapper/assets/38394463/5c7245aa-1923-415e-80b9-6d6be2649c79)

**Comment by shyam-dev** [comment]
The larger question is -- Was there a change made to the infrastructure
that lead to the change in results ?

**Comment by ramanan-ravi** [comment]
I did create a new S3 public bucket, yes
