### ISSUE TITLE
Remove irrelevant filters in report generation form

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#1747]
These filters are irrelevant for cloud compliance reports

![image](https://github.com/deepfence/ThreatMapper/assets/38394463/86ae0450-518c-47b0-8920-a4b3b033c9a7)

**Comment by shyam-dev** [comment]
We should replace the "Critical High Medium Low" with the actual relevant
filters.

**Comment by milan-deepfence** [comment]
https://github.com/deepfence/ThreatMapper/pull/1762
