### ISSUE TITLE
UI: Page shows error

### ISSUE THREAD

**Issue by milan-deepfence** [deepfence/ThreatMapper#1749]
Found some possible case that breaks UI.

1
![Image](https://github.com/deepfence/ThreatMapper/assets/111341101/aaff9b6f-a0e5-4119-835e-c0acbf55dc87)

2
![Image](https://github.com/deepfence/ThreatMapper/assets/111341101/30bd8df5-316f-403e-ba6b-0aa54ef4c6d8)

3

**Comment by shyam-dev** [comment]
A server restart should not cause the self signed certificate to change, unless new images were downloaded and those new images have a different self-signed certificate.

@noboruma  - Can we fix the build system to use a specific set of self-signed certificates with an option to re-generate it from the UI if needed ?

**Comment by noboruma** [comment]
A server restart does not change self signed certificate. 
Server is fully http based, the TLS layer comes from router (haproxy)
In practice, router image is cached and rarely rebuilt (if ever in dev setup).
If someone deployed new router image, then yes this error will occur but this is expected.

**Comment by manV** [comment]
In the case of this issue, the router image redeployment was likely the issue. Marking this done for now, we will reopen if issue is seen again.
