### ISSUE TITLE
Posture cloud masking fails

### ISSUE THREAD

**Issue by milan-deepfence** [deepfence/ThreatMapper#1753]
On posture cloud result, masking a node does not mask:
Payload:
{"mask_action":"mask_global","result_ids":["control.cis_v200_1_20--arn:aws::me-central-1:122565780891--cloud-node-aws-122565780891-1700633026"],"scan_id":"cloud-node-aws-122565780891-1700633026","scan_type":"CloudComplianceScan"}

**Comment by gnmahanth** [comment]
@manV please update the message to say `Masked Successfully and Control Disabled` for posture scan masking 

current message:
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/bac45431-4be5-4b5f-bd17-9f4497844738)

**Comment by manV** [comment]
Is this change applicable only for cloud posture results? Or all posture results? @gnmahanth

**Comment by gnmahanth** [comment]
this behavior is applicable for cloud posture only
