### ISSUE TITLE
Deleting scan history should be asynchronous

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#1761]
Right now deleting scan history should be synchronous. In case of large scan results, it will take many seconds to respond, which is not a good UX

**Comment by gnmahanth** [comment]
@manV the currently UI shows `Successfully Deleted` but this just initiates a async job, can you update the message to say something more appropriate like `Delete Requested Successfully` or something

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/9159685a-53ed-48de-a31e-fbc37341dab0)

**Comment by manV** [comment]
@gnmahanth Message was correct earlier but the behavior was changed in your PR above, we will make the messaging changes accordingly.
