### ISSUE TITLE
(feature-request): Modify existing integrations

### ISSUE THREAD

**Issue by shyam-dev** [deepfence/ThreatMapper#1777]
**Additional context**
Sometimes, there are changes to certain parts of an integration -- like minor changes to endopint, or changes to API key because the existing user is not using the platform anymore, etc.

In those scenarios, we need to delete and add the integrations again, which gets difficult when a large number of integrations are configure.

**Describe the solution you'd like**
A method to modify existing integrations.

Please see attached screenshot. We should be able to modify the api key if we know the previous API key and the new API key.

<img width="1509" alt="Screenshot 2023-11-27 at 1 02 28 PM" src="https://github.com/deepfence/ThreatMapper/assets/1436408/4c8e7ebf-998f-483d-aaca-6f7b99a06284">

**Comment by ibreakthecloud** [comment]
https://github.com/deepfence/ThreatMapper/pull/1818
