### ISSUE TITLE
Malware Scan not working on Docker compose installation on AWS EC2 instance c6a.2xlarge

### ISSUE THREAD

**Issue by chetancyberoi** [deepfence/ThreatMapper#1778]
**Describe the bug**
Threatmapper is deployed on AWS EC2 instance on c6a.2xlarge. Malware and secret scan is not working and getting the following error.

2023/11/28 05:18:37 [DEBUG] POST https://127.0.0.1:443/deepfence/controls/agent
Tue, 28 Nov 2023 05:18:41 +0000 ERR supervisor/process.go:141 Done with error: signal: trace/breakpoint trap (core dumped)
Tue, 28 Nov 2023 05:18:41 +0000 INF supervisor/process.go:155 /bin/bash -c "/opt/td-agent-bit/bin/fluent-bit -c /etc/td-agent-bit/fluentbit-agent.conf" restarting...
Tue, 28 Nov 2023 05:18:51 +0000 ERR supervisor/process.go:141 Done with error: signal: trace/breakpoint trap (core dumped)
Tue, 28 Nov 2023 05:18:51 +0000 INF supervisor/process.go:155 /bin/bash -c "/opt/td-agent-bit/bin/fluent-bit -c /etc/td-agent-bit/fluentbit-agent.conf" restarting...
Tue, 28 Nov 2023 05:18:52 +0000 INF router/openapi_client_controls.go:126 workloads = vuln: 0, secret: 0, malware: 0
Tue, 28 Nov 2023 05:18:52 +0000 INF router/openapi_client_controls.go:149 Workload: 2

**To Reproduce**
1. Install threatmapper using docker-compose on Amazon Linux 2023 AMI.
2. Start the Malware scan on the instance.

**Expected behavior**
Successful malware scan with proper results

**Screenshots**
![Screenshot 2023-11-28 at 11 16 27 AM](https://github.com/deepfence/ThreatMapper/assets/76002216/a0a5ed7e-e599-4cec-9782-932a2b6de1b9)

**Comment by ibreakthecloud** [comment]
@chetancyberoi this doesn't seems to be issue anymore. I was not able to reproduce it. Can you try with the latest release.

**Comment by chetancyberoi** [comment]
Verified with latest version
