### ISSUE TITLE
Kubernetes Cluster Scan Error

### ISSUE THREAD

**Issue by sm-joe** [deepfence/ThreatMapper#1836]
Hello Team,

While trying to initiate a Kubernetes Posture Scan, it fails after couple of minutes with no proper error message for troubleshooting.

Pls advise on how to get the scan completed successfully.

Container Runtime is containerd://1.6.19
Container Runtime Endpoint is unix:///run/containerd/containerd.sock
EKS version is 1.27
K8S agent is 2.1.0

**Comment by ramanan-ravi** [comment]
Hi @sm-joe , can you go to the scan details page and check?
![image](https://github.com/deepfence/ThreatMapper/assets/38394463/f9f40bdb-8ab8-4147-8570-ee3217f7fce3)

**Comment by ramanan-ravi** [comment]
Hi @sm-joe , thanks for reporting this.
Please redeploy deepfence agent helm chart with the latest version v2.1.0
