### ISSUE TITLE
Incorrect error message on fresh installation

### ISSUE THREAD

**Issue by shyam-dev** [deepfence/ThreatMapper#1841]
In a fresh installation, when a user provides random username and password to login without completing the registration process, we should show a correct error message instead of a generic error message

https://github.com/deepfence/ThreatMapper/assets/1436408/555effe1-4da6-4c92-82e1-604492bbf5c6

**Comment by milan-deepfence** [comment]
Related to this: https://github.com/deepfence/ThreatMapper/issues/1750
I did not see ERROR, I had seen invalid credentials instead.
