### ISSUE TITLE
Email Integrations - No Integration Type Error

### ISSUE THREAD

**Issue by sm-joe** [deepfence/ThreatMapper#1844]
Hello Team,

Trying to add a new email based integration for CloudCompliance notification type but getting below error.

Error - No integration type.

cronjobs/notification.go:137 Skipping integration for email rowId: 13 due to error: No integration type occured at last attempt
ERR cronjobs/notification.go:159 Error on integration No integration type

Pls advise.

**Comment by ibreakthecloud** [comment]
> Hello Team,
> 
> Trying to add a new email based integration for CloudCompliance notification type but getting below error.
> 
> Error - No integration type.
> 
> cronjobs/notification.go:137 Skipping integration for email rowId: 13 due to error: No integration type occured at last attempt ERR cronjobs/notification.go:159 Error on integration No integration type
> 
> Pls advise.

@sm-joe would you help me with few more details like:
- what version of ThreatMapper are you using?
- can you any screenshot?

**Comment by sm-joe** [comment]
I'm using the latest version - 2.1.0.

Console is already configured to send mails, other type of notification integration is working fine.

PFA the screenshot.

![image](https://github.com/deepfence/ThreatMapper/assets/146173441/451ac194-2a99-428d-9bc4-d835c7414dc2)
![image](https://github.com/deepfence/ThreatMapper/assets/146173441/940f5b46-193a-4338-b985-8a34a3caaaa3)

**Comment by ibreakthecloud** [comment]
> I'm using the latest version - 2.1.0.
> 
> Console is already configured to send mails, other type of notification integration is working fine.
> 
> PFA the screenshot.
> 
> ![image](https://private-user-images.githubusercontent.com/146173441/292128085-451ac194-2a99-428d-9bc4-d835c7414dc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDQ3NDEsIm5iZiI6MTcwMzE0NDQ0MSwicGF0aCI6Ii8xNDYxNzM0NDEvMjkyMTI4MDg1LTQ1MWFjMTk0LTJhOTktNDI4ZC05YmM0LWQ4MzVjNzQxNGRjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwNzQwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGQyNDM3MTcyNzBmZGE0ODc5ODI1NGNlMTFjOWE0ZGExYjk0NWU5MzVhMzVhZTcwMmNkMDcyYTU3ZTE5ZTk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TH1vHYMvQP7ux_IYfRYFyHa6TsPGevz23am-IaE4zts) ![image](https://private-user-images.githubusercontent.com/146173441/292128272-940f5b46-193a-4338-b985-8a34a3caaaa3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDQ3NDEsIm5iZiI6MTcwMzE0NDQ0MSwicGF0aCI6Ii8xNDYxNzM0NDEvMjkyMTI4MjcyLTk0MGY1YjQ2LTE5M2EtNDMzOC1iOTg1LThhMzRhM2NhYWFhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwNzQwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGEyYjkxZjYzZWQ1OGI3MDQxNTUxNzQxYmQ5OTY2M2Q0NmRjMGFiZjQ2OTJjOGY5ZTNjNTAyYTIzOWUzYTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ISSWhF1yAlC1Fe9ciExBCfGbqI_y7habzUwD4eudm7s)

@akumars1 can you verify this once. thanks!

**Comment by akumars1** [comment]
@ibreakthecloud 

Image Tag: 2.1.0
Reproducible : Yes

Steps To Reproduce:
1. Add Email Configuration
2. After Adding Email Configuration, Added Email based Cloud Compliance integration

Observation:
First It seems working as expected

Attachment:
<img width="1728" alt="Screenshot 2023-12-22 at 10 32 36 AM" src="https://github.com/deepfence/ThreatMapper/assets/111341228/62897d0a-9fc6-4067-b149-0e8ccb546b4a">

After 2 mins again checked it is showing No Alert Type

Attachment:

<img width="1728" alt="Screenshot 2023-12-22 at 10 35 49 AM" src="https://github.com/deepfence/ThreatMapper/assets/111341228/7a4ca4bd-0f51-4b1b-b2fb-78f6ae380508">

**Comment by ibreakthecloud** [comment]
cool thanks @akumars1 for validating and @sm-joe for raising it. I'm picking this up.
