### ISSUE TITLE
Scheduled task is not run in case that it is interrupted by neo4j restart

### ISSUE THREAD

**Issue by beMonika** [deepfence/ThreatMapper#1880]
**Describe the bug**
When some action (scan) is scheduled to run periodically it can be sometimes skipped due to restart of neo4j database. I assume it is restarted every 10 hours to perform backup (https://github.com/deepfence/ThreatMapper/blob/v2.1.0-rc1/deepfence_neo4j/df.sh). 

See error:
`[90mFri, 12 Jan 2024 02:00:00 +0000[0m [1m[31mERR[0m[0m cronjobs/scheduled_tasks.go:42 RunScheduledTasks: ConnectivityError: dial tcp <ip>:7687: connect: connection refused `
Used version: v2.1.0-rc1

**Expected behavior**
I would expect that scheduled job would run once neo4j is up again. Or it can be configurable in case that someone want their job to run at exact time.

**Comment by noboruma** [comment]
Hello @beMonika 
Thanks for reporting this issue. We have committed a fix:
https://github.com/deepfence/ThreatMapper/pull/1931
You can rebuild your console (only worker would be fine) and the issue should be gone.
