### ISSUE TITLE
[Threatmapper][kops version Version 1.22.2] Vulnerability scans failing

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#189]
**Describe the bug**
CVE scans  fail when all language packages are selected.

**To Reproduce**
1. Deploy agent and container as kops cluster on AWS.
2. The kops version is Version 1.22.2
3.  The agent is a 3 node cluster
4. Select any pod say "ip-172-20-56-215.us-west-1.compute.internal" and start CVE scan with all language package selected.
5. The advanced options also must be selected
![image](https://user-images.githubusercontent.com/34362153/147440344-ee7f2137-9b07-412b-9452-beb1072f7f8e.png)

6. Start a scan and the scans will fail with the following err message
7. 
![image](https://user-images.githubusercontent.com/34362153/147440394-e24b34c0-8e17-4170-89b5-95441e620034.png)

**Expected behavior**
When user selects "Scan entire cluster" for all language packages, CVE scans must work

**Screenshots**

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ramanan-ravi** [comment]
Error in agent
```
Error open /fenced/mnt/host/proc/sys/fs/binfmt_misc: too many levels of symbolic links while walk.
```
