### ISSUE TITLE
conflict in ingress values

### ISSUE THREAD

**Issue by lumattr** [deepfence/ThreatMapper#1991]
**Describe the bug**
https://github.com/deepfence/ThreatMapper/blob/main/deployment-scripts/helm-charts/deepfence-console/templates/deepfence-router-ingress.yaml#L1
and
https://github.com/deepfence/ThreatMapper/blob/main/deployment-scripts/helm-charts/deepfence-console/templates/NOTES.txt#L2

Confict in that one expected `enabled` and the other `enable`

They are also expecting different host structures. Notes wants a structure with `path` and ingress wants a string.

You get the following error if you use `enabled: true`:
```
UPGRADE FAILED: template: deepfence-console/templates/NOTES.txt:3:26: executing "deepfence-console/templates/NOTES.txt" at <.Values.ingress.host>: range can\'t iterate over [host]
```

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [x] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by gnmahanth** [comment]
@lumattr thanks for reporting the issue, please follow the steps from documentation at https://docs.deepfence.io/threatmapper/docs/console/kubernetes  
installing deepfence-router allows you to configure how you want to access the deepfence console
