### ISSUE TITLE
Syncing Gitlab SaaS registry faulty api reqest

### ISSUE THREAD

**Issue by daimoniac** [deepfence/ThreatMapper#1994]
**Describe the bug**
Whe using the Gitlab SaaS offering, threatmapper will not work with that as registry because of slightly different API behavior than on-prem gitlab installations.  

i used the following settings for the registry:
registry name: testreg
gitlab server url: https://gitlab.com
gitlab registry url: registry.gitlab.com/group/subgroup/project (private registry path consisting of group,subgroup and project)
gitlab access token: Personal access token with read_api and read_registry permissions

**To Reproduce**
1. Go to registries/gitlab/add new registry
2. add new registry using the variables posted above
3. Try to sync
4. See error in deepfence-worker

**Expected behavior**
gitlab registry added and images synced

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**
In https://github.com/deepfence/ThreatMapper/blob/318fcc16542ddac89591a0893ac74a92a305cf98/deepfence_server/pkg/registry/gitlab/client.go#L98, all projects are listed. In the context of SaaS gitlab, you will get a paginated list of _all_ public projects of all gitlab clients. Fixing this to

```
	url := fmt.Sprintf("%s/api/v4/groups/123456789/projects?private_token=%s&simple=false&membership=true", gitlabServerURL, accessToken)
```
with `123456789` being the group id of the client that contains all interesting projects reside should work fine.

I successfully worked around the bug by plugging in a reverse proxy that transforms this one api request accordingly.

```
              rewrite ^/api/v4/projects$ /api/v4/groups/${GROUP_ID}/projects break;
```

**Comment by shyam-dev** [comment]
Thank you for the update, @daimoniac. Do feel free to submit a patch too.

**Comment by daimoniac** [comment]
> Thank you for the update, @daimoniac. Do feel free to submit a patch too.

Would love to, but build is failing for me
```
Unable to find image 'deepfenceio/deepfence_agent:latest' locally
Error response from daemon: pull access denied for deepfenceio/deepfence_agent, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by ramanan-ravi** [comment]
Hello @daimoniac , the build issue is fixed now.
