### ISSUE TITLE
How do I use a port other than 443 for management console?

### ISSUE THREAD

**Issue by shrinidhi111** [deepfence/ThreatMapper#2]
I have a lot of applications running and of course 443 is not available.

How do I configure the management console to work on a port, other than 443?

Where should I change that setting if I am using 
- Docker or
- Standalone?

**Comment by ramanan-ravi** [comment]
At this point in time, we recommend that the installation may be done on a system that has the ports available as specified in the requirements. We will consider the ability to use different ports for future releases.

**Comment by shrinidhi111** [comment]
Thanks for the response!

Currently this is the only system that can support the given requirements, hence.

If you can point me to the configuration file in containers, then I can ssh into the specific container to change it.

Or if you guys can support overlay or bridge instead of host network in docker compose, then I can easily map the ports like all other containers.

Looking forward to try this!

**Comment by ramanan-ravi** [comment]
In couple of days we are releasing next version where we use overlay network instead of host network and you can change port 443 to some other port in docker compose file.
But ports 8000-8010 still need to be available.

**Comment by shyam-dev** [comment]
We have released a version that will help to access the management console on a port other than 443. It can be done by changing the port values here - https://github.com/deepfence/ThreatMapper/blob/master/files/docker-compose.yml#L89 . For example, if port 8080 is desired to be used, the line should now read "8080:443". The management console can now be access as https://<ip address>:8080/

Further, please note that the management console still needs port numbers from 8000-8010 available for its use.

Do take this release out for a spin and let us know.

**Comment by sandman137** [comment]
This is done and reported to be working, please re-open as needed.
