### ISSUE TITLE
Usage of external S3 compatible storage is not possible

### ISSUE THREAD

**Issue by pavels** [deepfence/ThreatMapper#2011]
If you want to use other store than AWS S3 or internal Minio, it is not possible because:

https://github.com/deepfence/ThreatMapper/blob/main/deepfence_worker/tasks/sbom/scan_sbom.go#L46
https://github.com/deepfence/ThreatMapper/blob/main/deepfence_worker/entrypoint.sh#L37

(there may be other places where this is hardcoded)

1) hardcoded `http` protocol
2) hardcoded `database` bucket name

It would be nice to:

1) use `DEEPFENCE_MINIO_DB_BUCKET` env variable already available instead of hardcoded value even for non aws endpoints
2) allow set protocol for non aws s3 endpoints

**Comment by shyam-dev** [comment]
Hello @pavels  — Thank you for raising this request. Is there a specific use-case scenario that you would like to address by using a storage other than S3 or minio ?

**Comment by pavels** [comment]
Yes, for us it would be either external Minio (we already have instance running on NAS) or external S3 like service (Ceph Object Gateway)

**Comment by ramanan-ravi** [comment]
Hello @pavels, once the next version (v2.2.0) is released, you will find the documentation here: https://docs.deepfence.io/threatmapper/docs/console/managed-database
