### ISSUE TITLE
autoscaling/v2beta1 no longer available as of 1.25

### ISSUE THREAD

**Issue by lumattr** [deepfence/ThreatMapper#2020]
**Describe the bug**
https://github.com/deepfence/ThreatMapper/blob/main/deployment-scripts/helm-charts/deepfence-console/templates/deepfence-worker.yaml#L122
and others.

See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [X] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by gnmahanth** [comment]
fixed in PR https://github.com/deepfence/ThreatMapper/pull/2030
