### ISSUE TITLE
Add documentation for AWS S3 fileserver

### ISSUE THREAD

**Issue by lumattr** [deepfence/ThreatMapper#2025]
**Additional context**
Could you add some documentation around how to use the AWS S3 fileserver you have in the helm chart [here](https://github.com/deepfence/ThreatMapper/blob/main/deployment-scripts/helm-charts/deepfence-console/values.yaml#L169-L184)?

**Is your feature request related to a problem? Please describe.**
I would like to move resources into managed services in AWS if i can. 

**Components/Services**

- [ ] UI/Frontend
- [X] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [X] Other (specify) Docs

**Comment by ibreakthecloud** [comment]
Hi @lumattr. Thanks for raising the issue. We'll update the docs with the steps.

**Comment by ramanan-ravi** [comment]
Hello @lumattr, once the next version (v2.2.0) is released, you will find the documentation here: https://docs.deepfence.io/threatmapper/docs/console/managed-database
