### ISSUE TITLE
Add smtp username and smtp from email field

### ISSUE THREAD

**Issue by gustysap** [deepfence/ThreatMapper#2048]
**Additional context**
Add smtp username and smtp from email field in email configuration
Because some SMTP server like sendgrid use apikey not email for authentication.
https://docs.sendgrid.com/for-developers/sending-email/integrating-with-the-smtp-api
![Threatmapper - Email Configuration](https://github.com/deepfence/ThreatMapper/assets/30117785/0407479d-1dbf-4849-a8e4-7b1f03b4e21d)

**Describe the solution you'd like**
A field to input the smtp username and smtp from email so we can configure the email address from what email and we can use some SMTP email need have SMTP username like sendgrid or other provider.

**Describe alternatives you've considered**
If threatmapper want to have feature for sendgrid email like AWS SES its will be better also.

**Components/Services**

- [x] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by ibreakthecloud** [comment]
@gustysap thanks for raising a issue. will update this issue with fixes if any.

**Comment by ibreakthecloud** [comment]
@gustysap The support for sendgrid in email configuration is merged to `main` branch. You can use the branch or can wait to for new stable release.
Thanks
