### ISSUE TITLE
Multiple workers deadlock each other when syncing ECR registries

### ISSUE THREAD

**Issue by lumattr** [deepfence/ThreatMapper#2054]
**Describe the bug**
Getting the following error form the workers running in EKS deployed from the console helm chart:
```
Tue, 02 Apr 2024 20:51:15 +0000 ERR registrysync/sync.go:100 failed to insert registry images batch 2 id=3 type=ecr error="Neo4jError: Neo.TransientError.Transaction.DeadlockDetected (ForsetiClient[transactionId=852032, clientId=47] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=848846, clientId=49]} on NODE(5417), because holders of that lock are waiting for ForsetiClient[transactionId=852032, clientId=47].\n Wait list:ExclusiveLock[\nClient[848846] waits for [ForsetiClient[transactionId=852032, clientId=47]]])" namespace=default
```

**To Reproduce**
1. Deploy deepfence-console helm chart using `values.worker.replicaCount: 3`
2. Add multiple registries in quick succession so they are all syncing. Im assuming starting a sync on multiple will also work.
3. Check logs of worker pods

**Components/Services affected**

- [ ] UI/Frontend
- [X] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by lumattr** [comment]
Getting the same error when tring to scan multiple ECR Registries:

```
Fri, 05 Apr 2024 10:24:53 +0000 ERR handler/scan_reports.go:248 Neo4jError: Neo.ClientError.Transaction.TransactionTimedOut (The transaction has been terminated. Retry your operation in a new transaction, and you should see a successful result. The transaction has not completed within the specified timeout (dbms.transaction.timeout). You may want to retry with a longer timeout. )
Fri, 05 Apr 2024 10:24:53 +0000 ERR ingesters/agent.go:994 Neo4j err: Neo4jError: Neo.TransientError.Transaction.DeadlockDetected (ForsetiClient[transactionId=1716601, clientId=15] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=1716590, clientId=16]} on NODE(5694), because holders of that lock are waiting for ForsetiClient[transactionId=1716601, clientId=15].
 Wait list:ExclusiveLock[
Client[1716590] waits for [ForsetiClient[transactionId=-1, clientId=18],ForsetiClient[transactionId=1716601, clientId=15]]])
Fri, 05 Apr 2024 10:24:54 +0000 ERR ingesters/agent.go:994 Neo4j err: Neo4jError: Neo.TransientError.Transaction.DeadlockDetected (ForsetiClient[transactionId=1716602, clientId=6] can't acquire ExclusiveLock{owner=ForsetiClient[transactionId=1716603, clientId=17]} on NODE(246473), because holders of that lock are waiting for ForsetiClient[transactionId=1716602, clientId=6].
 Wait list:ExclusiveLock[
Client[1716603] waits for [ForsetiClient[transactionId=1716602, clientId=6]]])
```

Steps: 
1. Have multiple AWS ECR registries configured (across multiple accounts, same region)
2. Navigate to the registries page
3. Tick all registries
4. Select "Start Scan" -> "Start Valnerability Scan"
5. Select settings (im using OS Packages, Javascript, Python)
6. Click "Start Scan"
7. Monitor logs for `deepfence-console-server` pod

**Comment by ramanan-ravi** [comment]
Hello @lumattr , neo4j deadlock error is fine. Recovering from this error is handled.

In case it happened during an action, like starting a scan, please retry again.
In case it happened during a background job, like adding registries, it will be retried automatically.

Did you notice any other issue during this?

**Comment by lumattr** [comment]
If its a non-issue im happy to close this. I does sync in the end i think. Its just a lot of spam messages which lead me to believe that it might be an issue.
