### ISSUE TITLE
Expanding cloud on topology page causes recursion error

### ISSUE THREAD

**Issue by lumattr** [deepfence/ThreatMapper#2055]
**Describe the bug**

I get the following error when clicking the plus icon on the "aws" line in the "clouds" tab on the topology page. 
```
React Router caught the following error during render InternalError: too much recursion
```

**To Reproduce**
1. Go to Topology
2. Click on the "Clouds" tab
3. Click the plus icon next to the cloud
4. See error page and above error repeated in the browser console

**Expected behavior**
Im not sure what its entending to show me. 

**Screenshots**
![image](https://github.com/deepfence/ThreatMapper/assets/118353335/f10e3721-2c24-436c-bee1-af16b5391270)
![image](https://github.com/deepfence/ThreatMapper/assets/118353335/f2d7c107-ae33-40d9-871e-b3b950edb95a)

**Components/Services affected**

- [X] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by gnmahanth** [comment]
@lumattr what is the tag of console container images you are using ?

**Comment by lumattr** [comment]
@gnmahanth The image tag is `2.1.0`

The response is:
<details><summary>response.json</summary>
<p>

```
{
    "nodes": {
        "aws": {
            "id": "aws",
            "label": "aws",
            "immediate_parent_id": "",
            "type": "cloud_provider"
        },
        "eu-west-1": {
            "id": "eu-west-1",
            "label": "eu-west-1",
            "immediate_parent_id": "aws",
            "type": "cloud_region"
        },
        "in-the-internet": {
            "id": "in-the-internet",
            "label": "The Internet (Inbound)",
            "immediate_parent_id": "",
            "type": "pseudo"
        },
        "eu-west-2": {
            "id": "eu-west-2",
            "label": "eu-west-2",
            "immediate_parent_id": "aws",
            "type": "cloud_region"
        },
        "900c86f4-16ea-425b-b634-0090eabdcb65": {
            "id": "900c86f4-16ea-425b-b634-0090eabdcb65",
            "label": "prod-k8s-cluster",
            "immediate_parent_id": "aws",
            "type": "kubernetes_cluster"
        },
        "dba6871c-349c-419a-843a-13a14133cce9": {
            "id": "dba6871c-349c-419a-843a-13a14133cce9",
            "label": "dev-k8s-cluster",
            "immediate_parent_id": "aws",
            "type": "kubernetes_cluster"
        },
        "9978256d-2b6d-4207-9056-8ad64da15b4f": {
            "id": "9978256d-2b6d-4207-9056-8ad64da15b4f",
            "label": "tools-k8s-cluster",
            "immediate_parent_id": "aws",
            "type": "kubernetes_cluster"
        },
        "422f39f1-40f2-4722-bccc-59c0df951baf": {
            "id": "422f39f1-40f2-4722-bccc-59c0df951baf",
            "label": "staging-k8s-cluster",
            "immediate_parent_id": "aws",
            "type": "kubernetes_cluster"
        },
        "us-east-1": {
            "id": "us-east-1",
            "label": "us-east-1",
            "immediate_parent_id": "aws",
            "type": "cloud_region"
        },
        "": {
            "id": "",
            "label": "",
            "immediate_parent_id": "aws",
            "type": "cloud_region"
        },
        "us-west-2": {
            "id": "us-west-2",
            "label": "us-west-2",
            "immediate_parent_id": "aws",
            "type": "cloud_region"
        },
        "out-the-internet": {
            "id": "out-the-internet",
            "label": "The Internet (Outbound)",
            "immediate_parent_id": "",
            "type": "pseudo"
        }
    },
    "edges": {}
}
``` 

</p>
</details>

**Comment by gnmahanth** [comment]
Hi @lumattr 
Thank you for reporting this, this was fixed in latest version of cloud scanner, 
please use cloud scanner image tag **`2.1.1`**

To fix this error on console you have to delete the cloud resource and regions where the value is empty

1. exec into neo4j container/pod
2. delete cloud resources where cloud_region is not set
```
cypher-shell -u neo4j -p $DEEPFENCE_NEO4J_PASSWORD --format plain "MATCH (n:CloudResource) where n.cloud_region="" detach delete n";
```
3. delete cloud region where node_id is not set
```
cypher-shell -u neo4j -p $DEEPFENCE_NEO4J_PASSWORD --format plain "MATCH (n:CloudRegion) where n.node_id="" detach delete n";
```

**Note:**  Please replace `$DEEPFENCE_NEO4J_PASSWORD` with your neo4j database password, if you are using default password you will find it [here](https://github.com/deepfence/ThreatMapper/blob/74b619e461e09f7d4095a3d399f4ea63d2208f6c/deepfence_neo4j/df.sh#L11)

**Comment by lumattr** [comment]
Hi @gnmahanth

Thank you for this, i will have a go and see if this fixes it. 

Would this also fix my [other issue](https://github.com/deepfence/ThreatMapper/issues/2044) by chance?

**Comment by lumattr** [comment]
Thank you. The above snippets fixed my issue.
