### ISSUE TITLE
Side panel doesn't show resources for secrets and malware

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#2077]
Vulnerability Side panel shows resources which has vulnerability

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/1be0a8f7-fbc2-4927-8dee-4856750d2e64)

Secret and Malware side panel doesn't have resources

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/b6eadded-a013-4f30-b694-7eeba12af6e1)

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/d6d101f5-d959-486c-a71e-a10a5f3e8e93)

**Comment by gnmahanth** [comment]
Not reproducible

**Comment by ramanan-ravi** [comment]
Resources will be empty when agents are disconnected. This list only includes hosts/containers from active agents.
