### ISSUE TITLE
Docs for Database Export and Import reference non-existent tag

### ISSUE THREAD

**Issue by lumattr** [deepfence/ThreatMapper#2080]
**Describe the bug**
[Docs page](https://community.deepfence.io/threatmapper/docs/console/database-export-import) references the deepfenceio/deepfence_backup:2.1.1 image which [doesnt exist on dockerhub](https://hub.docker.com/r/deepfenceio/deepfence_backup/tags)

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [X] Other - Docs

**Comment by ramanan-ravi** [comment]
Hello @lumattr, please follow these commands for exporting and importing the postgresql db.

- https://github.com/deepfence/ThreatMapper/blob/main/deepfence_postgres/pg-export.sh
- https://github.com/deepfence/ThreatMapper/blob/main/deepfence_postgres/pg-import.sh

Documentation will be updated in the next release - https://github.com/deepfence/ThreatMapper/blob/main/docs/docs/console/database-export-import.md#postgres-db-export-and-import
