### ISSUE TITLE
Add Namespace Filter in Pod Topology page and Container Topology page 

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#2103]
Add Namespace Filter in Pod Topology page and Container Topology page 

This make easier to find pods/containers in a particular namespace when kubernetes clusters are conneted 

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/a4eb33dd-a489-41fd-b788-ccda4c230f7c)
![image](https://github.com/deepfence/ThreatMapper/assets/22050509/86f3137f-29f5-4d7c-8526-e74717ca9b0b)

**Components/Services**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by milan-deepfence** [comment]
@ibreakthecloud @gnmahanth there will be need for searchNamespaces api which gives uniques namespace.
