### ISSUE TITLE
Inconsistent state when filters without results are applied

### ISSUE THREAD

**Issue by shyam-dev** [deepfence/ThreatMapper#2106]
**Describe the bug**

When a filter is applied on a set of posture results, if there are no entries for that result, the error shown on the browser does not provide the complete information

**To Reproduce**

Please see the attached video

**Expected behavior**

Whenever a filter is applied and if there are no results for that filter, a proper message should be shown to the user

**Components/Services affected**

- [x] UI/Frontend
- [x] API/Backend

https://github.com/deepfence/ThreatMapper/assets/1436408/1619575c-feb4-4784-8860-e3e9669fc43e

**Comment by milan-deepfence** [comment]
@shyam-dev @ramanan-ravi As we checked the issue and we could not reproduce it. Can this be closed?
