### ISSUE TITLE
Hosts page show scan error when newer successful scan exists

### ISSUE THREAD

**Issue by lumattr** [deepfence/ThreatMapper#2109]
**Describe the bug**
On the topology page, hosts tab, table view, I have a bunch of hosts showing errors, and have been trying to debug why they are showing error. Apparently they are fine now, but the page is misleading me. It seems like the page is showing a result from a previous scan, not the latest result. I dont know if this effects all scan types but im seeing it for secret and malware scans.

**To Reproduce**
1. Have an older, failed scan, and a newer successfull one. 
2. go to the topology page, hosts tab, table view
4. See shown errors
5. Open scan results through host
6. open drop down for scan times

**Expected behavior**
Page should show latest scan result on the table layout

**Screenshots**
![image](https://github.com/deepfence/ThreatMapper/assets/118353335/0b3b3f63-3ae6-4437-9946-195c97dc39cb)
![image](https://github.com/deepfence/ThreatMapper/assets/118353335/a5da2134-340a-49d4-bba5-27b1b2eeccd8)
![image](https://github.com/deepfence/ThreatMapper/assets/118353335/1b4884f7-71df-4f2e-89ea-4d2c379efb94)

**Components/Services affected**

- [X] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by ramanan-ravi** [comment]
Hello @lumattr this was already fixed [here](https://github.com/deepfence/ThreatMapper/pull/2047).
Request you to upgrade to v2.2.0 once it is released.
