### ISSUE TITLE
Cloud Posture Interface filter uses the incorrect benchmark type for SOC2

### ISSUE THREAD

**Issue by tektite-io** [deepfence/ThreatMapper#2148]
**Describe the bug**
The cloud posture result interface allows filtering by benchmark type; however in the filter the value is SOC2 while in the scan result is SOC_2 , and therefore applying such filter will show no results.

**To Reproduce**
1. Go to Posture
2. Click on AWS
3. Click on one Account (assuming that there is a SOC2 scan result)
4. Select filter and pick SOC2
5. No results are diplayed

**Expected behavior**
Selecting SOC2 should filter by SOC2 benchmark type and show the correct results

**Components/Services affected**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**
A quick fix would be to replace the SOC2 with SOC_2 in ComplianceScanConfigureForm.tsx
``` 
  aws: ['CIS', 'NIST', 'PCI', 'HIPAA', 'SOC_2', 'GDPR'],
  aws_org: ['CIS', 'NIST', 'PCI', 'HIPAA', 'SOC_2', 'GDPR'],
```

**Comment by milan-deepfence** [comment]
Fix: https://github.com/deepfence/ThreatMapper/pull/2149
Note: We are implementing another better approach to avoid such similar bugs in the future.
