### ISSUE TITLE
Google Artifact Registry Not in V2

### ISSUE THREAD

**Issue by sjkeerthi** [deepfence/ThreatMapper#2176]
**Registery**
Please Include the GAR [Google Artifact Registry]  under Registries Menu

Recently google cloud have announced there GCR service will be end so all the GCR will be moved to GAR

When I tried in the latest version of Threadmapper I came accross there is only options to add GCR not GAR since GAR  change the URL as for example `europe-west2-docker.pkg.dev/<projectname>/<reponame>` when I tried to add 

![image](https://github.com/deepfence/ThreatMapper/assets/4696166/7974b569-62a0-4bfe-ad99-386e8ffc7f23)

Kindly update GAR 

Thank you so much for the Effort and great work really appriciated all the Developer who contributies to Deepfence 
Good Work Keep it up

**Comment by ibreakthecloud** [comment]
@sjkeerthi this is a very valid issue. Thanks for raising. I'll take a look at it.
Maybe we can add GAR along-side GCR, till GCR is still being supported by Google Cloud

**Comment by ibreakthecloud** [comment]
Hey @sjkeerthi ThreatMapper can list GAR images too currently using same method. GCR url ends with `gcr.io` and GAR ends with `pkg.dev`. In the URL field put only the GAR url starting with `https`, for example, `https://europe-west2-docker.pkg.dev`.
LMK if that worked. Thanks

**Comment by sjkeerthi** [comment]
I tried by adding the url as you mentioned https:///europe-west2-docker.pkg.dev it accepted and saved it. But whenever I click always I could see its keep main screen Syncing. 

![image](https://github.com/deepfence/ThreatMapper/assets/4696166/b2879508-6081-4c23-a105-2e1c9a4d005a)

**Comment by sjkeerthi** [comment]
In the log when I click the scan I could see

`Fri, 07 Jun 2024 19:29:13 +0000 ERR gcr/client.go:149 invalid character '<' looking for beginning of value
Fri, 07 Jun 2024 19:29:13 +0000 ERR gcr/client.go:52 invalid character '<' looking for beginning of value
Fri, 07 Jun 2024 19:29:13 +0000 ERR cronjobs/registry.go:95 unable to sync registry: google_container_registry (GAR): invalid character '<' looking for beginning of value namespace=default
Fri, 07 Jun 2024 19:29:15 +0000 ERR gcr/client.go:149 invalid character '<' looking for beginning of value
Fri, 07 Jun 2024 19:29:15 +0000 ERR gcr/client.go:52 invalid character '<' looking for beginning of value
Fri, 07 Jun 2024 19:29:15 +0000 ERR cronjobs/registry.go:95 unable to sync registry: google_container_registry (GAR): invalid character '<' looking for beginning of value namespace=default
Fri, 07 Jun 2024 19:29:16 +0000 INF cronjobs/neo4j.go:843 Retry scan DB Starting namespace=default`

**Comment by ibreakthecloud** [comment]
@sjkeerthi can you verify if the auth json provided is valid?

**Comment by sjkeerthi** [comment]
Yes its a valid one which I validated by docker login and did docker pull with that json file.

**Comment by sjkeerthi** [comment]
It's been fixed I delete and added again and it worked :)
