### ISSUE TITLE
How to get Information about an Error?

### ISSUE THREAD

**Issue by 53845714nF** [deepfence/ThreatMapper#2214]
**Describe the bug**
How to get more Information about an Error?

**To Reproduce**
I have a Privat Docker Registry and want a vulnerability scan but get an Error.

**Expected behavior**
More Information what's wrong 

**Screenshots**
![image](https://github.com/deepfence/ThreatMapper/assets/48125666/4a55da95-e22b-413c-ac5e-9d1eac194104)

**Components/Services affected**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by ramanan-ravi** [comment]
Hello @53845714nF, please hover over the red exclamation mark to get the error details

**Comment by 53845714nF** [comment]
![image](https://github.com/deepfence/ThreatMapper/assets/48125666/613cd3d3-afb2-4dc5-8842-439d477e937b)
Mhh, get nothing, use KDE tested on Firefox and Chromium.

**Comment by manV** [comment]
I think it is better to link to the actual scan page where the error details can be viewed by hovering over the error icon. I have added the changes at [#2216](https://github.com/deepfence/ThreatMapper/pull/2216)

For now, error info can be viewed by manually navigating to relevant scan page by going to vulnerabilities > view all scans > click on failed scan > hover over error icons on the scan page.

**Comment by 53845714nF** [comment]
Give me two days and I'll take a look.

**Comment by 53845714nF** [comment]
Cool, I see the Error.
