### ISSUE TITLE
Private cloud - Remove nodes marked as 'Unknown' from topolgy

### ISSUE THREAD

**Issue by sandman137** [deepfence/ThreatMapper#229]
**Describe the bug**
When ThreatMapper sensors run on OpenShift or any on prem environment the typical cloud->region->computes hierarchy is not present. Due to this a lot of nodes get marked as 'Unknown'. 

**To Reproduce**
Install sensors anywhere outside public cloud to see this issue. 

**Expected behavior**
We shouldnt expect a rigid hierarchy like cloud->region->compute etc. Ideally this will be solved with ability to filter on various types of computes:
E.g. show 
- VMs
- Pods
- Fargate instances
- Functions (roadmap)

But for existing openshift users, this has to be solved by simply not rendering any nodes and edges (esp meta nodes like cloud region) that are identified as 'Unknown' and instead expanding the children node recursively

 i.e. unknown -> unknown -> node N -> processes should end up in direct expansion of node N

**Screenshots**

![image (3)](https://user-images.githubusercontent.com/35167551/150731885-acb1ca50-3e99-4fca-8caf-64153fbdc419.png)

**Components/Services affected**

- [x] UI/Frontend

**Comment by ramanan-ravi** [comment]
We will rename "Unknown" cloud node to "Private Cloud" and rename "Unknown" region node to "Zone"

**Comment by sandman137** [comment]
Here is the GUI in action now
![image (4)](https://user-images.githubusercontent.com/35167551/151291485-3dedd344-1a6a-41ba-9ff5-7e1336e4e84a.png)
