### ISSUE TITLE
Error in Installation of deepfence-agents in k8s cluster with istio

### ISSUE THREAD

**Issue by Chhaya22** [deepfence/ThreatMapper#231]
When trying to install deepfence-agents in k8s cluster using helm chart encountered below shown error message. K8s cluster uses Istio
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: Namespace "deepfence" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "deepfence-agent"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "deepfence"

**Comment by saurabh2253** [comment]
Update on steps performed:

- Installed istio from here https://istio.io/latest/docs/setup/getting-started/
- `helm repo add deepfence https://deepfence-helm-charts.s3.amazonaws.com/threatmapper`
- helm install deepfence-agent deepfence/deepfence-agent \
    --set managementConsoleUrl=137.184.54.232 \
    --set deepfenceKey=fa612581-622e-42a5-ac16-cdc7b043e3c7
- The cluster is visible in https://threatmapper.deepfence.show/#/topology without issue/error logs

**Comment by saurabh2253** [comment]
Enabled cni and retried
- `istioctl profile dump` to default config
- in the yaml file set 
  ```
 apiVersion: install.istio.io/v1alpha1
   kind: IstioOperator
   spec:
     components:
       base:
         enabled: true
       cni:
         enabled: true
```
- In new cluster installed istio using yaml file`istioctl install -f my-config.yaml `
- `kubectl label namespace default istio-injection=enabled`
- ```
helm install deepfence-agent deepfence/deepfence-agent \
    --set managementConsoleUrl=<threatmapper_ip> \
    --set deepfenceKey=xxx
```
This is working too on DigitalOcean

**Comment by saurabh2253** [comment]
Update :
Agents are now running for @Chhaya22 
Solved by removing namespace override in helm install command
```
helm install --namespace deepfence deepfence-agent deepfence/deepfence-agent \
    --set managementConsoleUrl=XXXXXXX \
    --set deepfenceKey=XXXXXXXXXXXXX  --namespace deepfence
```
