### ISSUE TITLE
Vulnerability Scan with priority

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#232]
- If vulnerability scan is started on more than 15 hosts / images, they will be queued and processed once previous scans are complete.
- If a new scan is started, it will be added to the end of the queue
- We need to introduce priority to this so that the image which needs to be scanned immediately is added to the start of the queue

**Comment by mukuldeepfence** [comment]
Solution has been incorporated here https://github.com/deepfence/ThreatMapper/issues/109
