### ISSUE TITLE
Error when register: Console URL is not valid

### ISSUE THREAD

**Issue by jonahbohlmann** [deepfence/ThreatMapper#233]
**Describe the bug**
I started with the getting started page with docker-compose. After starting the services, I can enter the portal and click on "Register". 
After I filled the form, I got the error "Console URL is not valid"

**To Reproduce**
1. Go to this page: https://github.com/deepfence/ThreatMapper/wiki/Installing-the-Management-Console
2. Follow instruction in section: "Install the ThreatMapper Management Console - Single Docker Host"
3. Go to web-portal "https://localhost/"
4. Click on register
5. Enter your details
6. Click on button to submit form
7. Got the error "Console URL is not valid"

**Expected behavior**
Registration should be successfull to be able to login into the web-ui.

**Screenshots**
![image](https://user-images.githubusercontent.com/9147768/151036825-4a2a7363-eb8f-47bc-bd31-dc03fdc83da9.png)

**Components/Services affected**

- [X] UI/Frontend
- [X] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**
None

**Comment by shyam-dev** [comment]
Can you try using https://<ip_address>/ instead of trying to use
https://<localhost>
?

**Comment by jonahbohlmann** [comment]
Thanks, that worked!

**Comment by jonahbohlmann** [comment]
How can I change the URL? When I now try to deploy that on a docker-node, I get again that issue. Using the IP is not really nice for us.

**Comment by shahpratikr** [comment]
@jonahbohlmann using http://localhost I was able to register myself. can you please verify with latest docker-compose file? cc: @ramanan-ravi @shyam-dev

**Comment by ramanan-ravi** [comment]
> How can I change the URL? When I now try to deploy that on a docker-node, I get again that issue. Using the IP is not really nice for us.

@jonahbohlmann Please use latest version v1.3.1

**Comment by saurabh2253** [comment]
Closing issue as it has been inactive for more than a month now.
