### ISSUE TITLE
GCP Cloud Run - Scan problem

### ISSUE THREAD

**Issue by serg-adm** [deepfence/ThreatMapper#2333]
**Describe the bug**
After upgrading from version 2.2 to ThreatMapper 2.4, I cannot add a GCP project and are left with an empty project that cannot be deleted.
I tried to deploy fresh ThreatMapper, but I can't add Posture - GCP via GCP Cloud Run single project.
On version 2.2 all worked.
**To Reproduce**
1. Go to Terraform
2. Deploy  version 0.8.0
3. Empty Posture - GCP

**Expected behavior**
Want to scan GCP Project

**Screenshots**
![Screenshot 2024-10-08 at 13-17-59 Posture Accounts Deepfence](https://github.com/user-attachments/assets/010b4562-6015-431d-b4a6-fd88117a1bcf)

**Components/Services affected**

- [x] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [x] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by ramanan-ravi** [comment]
Hello @serg-adm , please go to `Settings` -> `Scan history and db management` and delete the cloud posture. You can now delete the GCP account in posture page.

**Comment by serg-adm** [comment]
Hello @ramanan-ravi ! Thank you for help!
Same result
![Screenshot 2024-10-08 at 13-26-54 Scan History   Database Management Deepfence](https://github.com/user-attachments/assets/52c4485a-1183-4a9d-99d0-2d5b8eaa4232)
![Screenshot 2024-10-08 at 13-27-30 Posture Accounts Deepfence](https://github.com/user-attachments/assets/c403354d-d319-40c4-9dba-7636d5482627)

**Comment by serg-adm** [comment]
What is strange, that on fresh install threatmapper , i can't add my GCP project too. I tried different projects, same result.

**Comment by serg-adm** [comment]
The Delete option is not available. Constantly spinning.
![изображение](https://github.com/user-attachments/assets/38e5f6ca-0f6c-4c39-ad34-40def614a547)

**Comment by ramanan-ravi** [comment]
https://github.com/deepfence/ThreatMapper/issues/2333#issuecomment-2399468187

Please select the cloud posture option here and try again

**Comment by serg-adm** [comment]
This work, thank you!
