### ISSUE TITLE
Integration - account filter for Cloud Posture Scan

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#2344]
In integrations, when account filter is set for Cloud Posture scan results, the results are not sent at all.
It works fine when account filter is not set.

![image](https://github.com/user-attachments/assets/efacb220-c100-4a33-b19c-77dde364350d)

**Comment by gnmahanth** [comment]
@manV please change `node_type` to value of `cloud_provider` instead of value `cloud_account` for cloud compliance scans 

![image](https://github.com/user-attachments/assets/35cc53b6-0b3d-43c5-b469-6c2fe173d48a)

**Comment by gnmahanth** [comment]
fix issue related to all cloud providers selected when compliance scan is selected and no cloud node id are selected, added a new filed `cloud_provider` which is required when integration type is cloud compliance scan 
```
{
  "node_ids": [],
  "cloud_provider": "aws",
  "fields_filters": {
    "match_filter"            : {"filter_in": null },
    "order_filter"            : { "order_fields": null},
    "compare_filter"          : null ,
    "contains_filter"         : {"filter_in": null },
    "not_contains_filter"     : {"filter_in": null },
    "match_in_array_filter"   : {"filter_in": null },
    "contains_in_array_filter": {"filter_in": null }
  },
  "container_names": []
}
```
