### ISSUE TITLE
Posture scan - deepfence docker agent itself is not compliant...

### ISSUE THREAD

**Issue by html5maker** [deepfence/ThreatMapper#2367]
The Posture Scan is showing a lot of warning about the deepfence agent docker container:
<img width="2312" alt="image" src="https://github.com/user-attachments/assets/1efefccb-dcde-4146-b883-05e491e3998a">
The ThreatMapper default config should be fully compliant out of the box...

**Comment by ramanan-ravi** [comment]
Hello @html5maker, deepfence agent mounts the host's file system onto the agent container at `/fenced/mnt/host`. These vulnerabilities are found in the host where agent is running. (Agent only has docker client, not the server)
