### ISSUE TITLE
Cannot start scans with API token

### ISSUE THREAD

**Issue by lumattr** [deepfence/ThreatMapper#2372]
**Describe the bug**
Using an API token retrieved from `/deepfence/auth/token` i am unable to start a scan using `/deepfence/scan/start/vulnerabilities`

This is due to the `licence_active` field in the JWT token [being set to false](https://github.com/deepfence/ThreatMapper/blob/release-2.5/deepfence_server/handler/auth.go#L65-L66)

I can retrieve a token from the endpoint fine becuase its under the public api, and i can search for hosts fine as the main authenticated api only checks [for signature validity](https://github.com/deepfence/ThreatMapper/blob/release-2.5/deepfence_server/router/router.go#L183).

But the scan start endpoint [checks if the license is active](https://github.com/deepfence/ThreatMapper/blob/release-2.5/deepfence_server/router/router.go#L376), by [reading the value](https://github.com/deepfence/ThreatMapper/blob/release-2.5/deepfence_utils/directory/context.go#L52) of the `license_active` key. 

I also checked the refresh endpoint (`/deepfence/auth/token/refresh`) and that can set the field to true, but only is the [grant type is from a password](https://github.com/deepfence/ThreatMapper/blob/release-2.5/deepfence_server/handler/auth.go#L93)

**To Reproduce**
```
export ACCESS_TOKEN=$(curl -X POST -d "{\"api_token\": \"${THREATMAPPER_TOKEN})\"}" https://threatmapper-console/deepfence/auth/token | jq -r '.access_token')
curl -i -X POST -H "Authorization: Bearer $ACCESS_TOKEN" -d '{"node_ids":[{"node_id":"a-node-id","node_type":"host"}],"scan_config":[{"language":"base"}]}' https://threatmapper-console/deepfence/scan/start/vulnerability
```
Gives you:
```
HTTP/2 402
date: Wed, 20 Nov 2024 22:59:39 GMT
content-type: text/plain; charset=utf-8
content-length: 17
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000; includeSubDomains
cross-origin-resource-policy: same-origin
cross-origin-opener-policy: same-origin
cross-origin-embedder-policy: require-corp

Payment Required
```

**Expected behavior**
I have a license so the scan should be started

**Components/Services affected**

- [ ] UI/Frontend
- [X] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by ramanan-ravi** [comment]
Hello @lumattr, thanks for the detailed analysis of the issue. We will fix this.
