### ISSUE TITLE
crontab rewritten after agent installed

### ISSUE THREAD

**Issue by mareban** [deepfence/ThreatMapper#2376]
Hi,

i've installed the agent on some ubuntu linux boxes but i was surprised that the root crontab was rewritten with this line :

*/5 * * * * /usr/sbin/logrotate /opt/deepfence/df-agents/machinename/etc/logrotate.d/fenced_logrotate.conf

Is there a backup of the previous crontab otherwise it should be and mentionned somewhere :-( !

Thanks for your help.

**Comment by ramanan-ravi** [comment]
Hello @mareban, thanks for notifying the issue. The fix will be released soon.

**Comment by ramanan-ravi** [comment]
Fixed in [v2.5.1](https://github.com/deepfence/ThreatMapper/releases/tag/v2.5.1)
