### ISSUE TITLE
Custom Mountpath containerd.sock on K3S

### ISSUE THREAD

**Issue by topahadzi** [deepfence/ThreatMapper#239]
**Describe the bug**
I Install the deepfence-agent on k3s cluster, i use helm chart for installing the agent but i got my deepfence agent pod its still in ContainerCreating state its because the pod cannot mount the containerd.sock. i can resolve this issue by deleting "type: socket" on the daemonset. next issue i must change the default mountpath for containerd.sock because the default containerd path from k3s is different its on "/run/k3s/containerd/containerd.sock"

**To Reproduce**
1. Install deepfence agent on k3s cluster using helm chart

**Expected behavior**
You can add custom setting on helm chart values to edit the mount setting, and i don't need to change the daemonset directly

**Components/Services affected**

- [x] Other (Deepfence Agent)

**Comment by saurabh2253** [comment]
@topahadzi 
Can you specify the cloud provider you are using and the version of k3s?

**Comment by ramanan-ravi** [comment]
@saurabh2253 TODO: make the socket path fully configurable from helm chart

**Comment by saurabh2253** [comment]
@topahadzi We can now deploy sensor agents on k3s by setting the mountContainerRuntimeSocket. containerdSockPath variable in values yaml file.
<img width="1219" alt="Screenshot 2022-02-03 at 12 48 04 PM" src="https://user-images.githubusercontent.com/3922581/152298179-f53c0bec-1987-4a49-ac25-fcda68df4124.png">

**Comment by topahadzi** [comment]
thanks for the update i will try it
