### ISSUE TITLE
Unable to navigate from 'Topology'

### ISSUE THREAD

**Issue by lwilliams1990** [deepfence/ThreatMapper#24]
Hi,

I've setup the management console on an AWS instance using the repository instructions. I've registered an account and accessed the console but I can't navigate to any other pages (registries, vulnerabilities, settings etc.). It seems to be in a loop of 'resuming the live state' and is stuck 'Optimizing hosts'.

I've given it over 60 minutes as the readme mentioned, but there's been no change.

I can't find any obvious problems looking through the various container logs. I wondered if someone here could offer any guidance?

**Comment by sandman137** [comment]
Hi @lwilliams1990 , can you confirm that the ec2 instance being used has 8 cores/16G RAM/120GB disk config as mentioned in the readme? Would also help if you can share a screengrab of the console while I try to reproduce the issue locally.

**Comment by sandman137** [comment]
Quickly tried the installation at my end. Here is how it should look upon successful install.

You should see 1 host node on topology, Vulnerability db as a status on status bar. Menus Topology, Registries, Integrations and Settings should work as shown below. Other menus like compliance etc are disabled and will be removed from threatmapper screen as they don't belong here in community edition.  


Topology screen

<img width="1675" alt="Screenshot 2020-06-07 at 8 58 14 PM" src="https://user-images.githubusercontent.com/35167551/83973102-b2ea9180-a901-11ea-8193-9a6f58ac7b03.png">

Registries
<img width="1474" alt="Screenshot 2020-06-07 at 9 01 10 PM" src="https://user-images.githubusercontent.com/35167551/83973146-14aafb80-a902-11ea-8161-6b09ddc7fcea.png">

**Comment by lwilliams1990** [comment]
Hi,

Thanks for responding!

I gave it a c5.2xlarge aws instance with a 120gb root volume. I'm building the environment with Terraform / Ansible so I've just shared that publicly here:

https://github.com/lwilliams1990/deepfence-threatmapper-lab

The view I see when I connect in to the web console on the instance's public IP is this:

![Screenshot from 2020-06-07 18-07-51](https://user-images.githubusercontent.com/51878981/83975113-ee796180-a8e9-11ea-97ed-6cd3c31e8e15.png)

**Comment by shyam-dev** [comment]
Hello @lwilliams1990 - 

Can you please attach the output of the following command here -- 

for i in $(docker ps --format "table {{.Names}}");do echo "*****"$i"****">>/tmp/logs.txt;docker logs $i >> /tmp/logs.txt 2>&1 ;done

The output will be in the file /tmp/logs.txt. 

On the face of it, this seems to be a configuration issue, and we will help you resolve it.

**Comment by shyam-dev** [comment]
Also, are you using a VPN service ?

**Comment by lwilliams1990** [comment]
Thanks for your help! The requested logs are here:

[logs.txt](https://github.com/deepfence/ThreatMapper/files/4742650/logs.txt)

I am using NordVPN on my laptop, I'm not sure why that would matter but I just tried provisioning and connecting in with it disabled and it is the same.

**Comment by shyam-dev** [comment]
Hello @lwilliams1990 

Thank you for sending out the logs to us. 

Looking at the logs, this seems to be a client side issue. We use websockets extensively, and it is known that certain browser extensions and VPN software block connections to websockets.

Can you please try the following -- 

1. Start a browser window in incognito mode, with all extensions disabled, and try to access the Management Console ?
2. Try to access the management console from a different system ?

Thanks

**Comment by lwilliams1990** [comment]
Hi,

I've re-provisioned again using the same Terraform configuration previously mentioned to try again. I've tried with incognito and extensions disabled:

On Ubuntu 20.04:
Firefox 76.0.1 (64-bit)

Windows 10 1903:
Chrome 83.0.4103.61
Edge 83.0.478.44

I see the issue across all of these.

**Comment by sandman137** [comment]
Thanks for sharing these details. Looks like we need to take a closer look, happy to help you triage live. Looks mostly like a config issue, not sure where though! Could you share your email at community at deepfence dot io. Will share hangout/slack details with you.

**Comment by ramanan-ravi** [comment]
Hello @lwilliams1990 

Please join us on Slack [here](https://join.slack.com/t/deepfencecommunity/shared_invite/zt-exqn0n82-2lvZLZmlPAiwsW9_JcUUyA) for support.

**Comment by lwilliams1990** [comment]
Issue was caused by the AWS security group rule being set as HTTPS instead of TCP/SecureTCP. This prevents Deepfence websockets working correctly.
