### ISSUE TITLE
Scans failing to pick up RedHat RPMs

### ISSUE THREAD

**Issue by sgreenslade** [deepfence/ThreatMapper#256]
**Describe the bug**
I'm scanning RH 7.7 machines with the Bare-Metal / Docker container configuration.
I get results back for application code Java, Python, etc. But nothing about the RPMs and packages installed.

**To Reproduce**
1. Install RH 7.7 - Might be tricky to find the ISO....
2. Docker Won't install on RH 7.7 so you'll need to add some Centos packages
`sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm --nogpgcheck`
`sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/slirp4netns-0.4.3-4.el7_8.x86_64.rpm --nogpgcheck`
`sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/fuse3-libs-3.6.1-4.el7.x86_64.rpm --nogpgcheck`
`sudo yum -y install http://mirror.centos.org/centos/7/extras/x86_64/Packages/fuse-overlayfs-0.7.2-6.el7_8.x86_64.rpm --nogpgcheck`
`sudo yum -y install docker-ce docker-ce-cli containerd.io`

3. Then start docker and run the Sensor Agent as per the documentation.
4. Run a scan with all options enabled.

**Expected behavior**
I'd expect to see details of the RPMs with CVEs that need updating.

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [ X] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**
Both the Agent and Management Console are running as virtual machines (Oracle Virtual Box) on my laptop.
I wanted to do a scan of RH 7.7 before updating to RH 7.9 to see how many CVEs get fixed, and how many remain.

**Comment by sgreenslade** [comment]
I've been Scanning Fedora 33 & 34 machines as well, and they also seem to be missing the OS Packages.

**Comment by sgreenslade** [comment]
I've also scanned an Ubuntu Server 21.04 install, and that found 0 Vulnerabilities.
So either the OS installs I've tried are all perfectly up-to-date... or scanning of Linux packages seems to not be working.

**Comment by sandman137** [comment]
Looks like the underlying cve db isnt updated or is being updated during the scans, could you share the diagnostic logs here or on slack. You should be able to find those in settings -> diagnosis (dont need agent logs just the console logs). Do you also see something as follows on that page?

"Threat Intel feeds updated 2.9 hours ago"

**Comment by sgreenslade** [comment]
Thanks.
I'll send them to you on Slack.
I can see on that page three green status icons and the text:

"Threat Intel feeds updated 11.9 hours ago"

**Comment by sandman137** [comment]
Could you check now? This should work, please try release 1.3

**Comment by sgreenslade** [comment]
Hi Sandman,
Thanks for following up on this.

I've upgrades the Management console to 1.3 and stopped the Agent, deleted and re-downloaded the Agent image.
The Management console is running 1.3
The Agent is still running 1.2.

Scans fail quickly with the following error, saying the kernel 3.10 is not supported :-(


```
time="2022-03-16T18:51:11Z" level=info msg="publishing to: https://xxxx:443"
<probe> INFO: 2022/03/16 18:51:11.775303 Basic authentication disabled
<probe> INFO: 2022/03/16 18:51:11.863699 command line args: --mode=probe --no-app=true --probe-only=true --probe.cri=false --probe.docker=true --probe.docker.interval=10s --probe.endpoint.report=true --probe.insecure=true --probe.log.level=info --probe.processes=true --probe.publish.interval=10s --probe.spy.interval=5s --probe.token=<elided> --weave=false xxxx:443
<probe> INFO: 2022/03/16 18:51:11.863790 probe starting, version 5a1c201, ID 778a667b370d1724
<probe> INFO: 2022/03/16 18:51:11.875155 Control connection to xxxx starting
<probe> WARN: 2022/03/16 18:51:11.981935 Error setting up the eBPF tracker, falling back to proc scanning: kernel not supported: got kernel 3.10.0-1160.53.1.el7.x86_64 but need kernel >=4.4
<probe> ERRO: 2022/03/16 18:51:11.982887 plugins: problem loading: no such file or directory
<probe> INFO: 2022/03/16 18:51:12.164064 Publish loop for xxxx starting

```

**Comment by sandman137** [comment]
@saurabh2253 could you please take a look? That's an old kernel but we should fall back to conntrac. 

@sgreenslade by the way, you need to upgrade agent to 1.3 as well.

**Comment by sgreenslade** [comment]
Thanks Sandman.

I did try to update the agent, but didn't get the v 1.3. I stopped the
container, purged and deleted the downloaded image.
Then started the agent and it downloaded the latest version, but it was the
same 1.2.
My servers are in AWS, so perhaps AWS has a docker repository that has not
picked up the 1.3 yet?

Will try again later.

**Comment by sgreenslade** [comment]
Ah... on the agent docker image, the latest tag has not been bumped, so it's still pointing to 1.2.
If I start the agent with the explicit version then I get 1.3 and the scan seem to run....

deepfenceio/deepfence_agent_ce:1.3.0

Please can you update the latest tag or the documentation?

**Comment by shyam-dev** [comment]
Thank you for pointing it out @sgreenslade. We will sort it out.

**Comment by sgreenslade** [comment]
I'm very happy to report that using v1.3 Management Server and Agent (with an increase to the ES memory).
I'm not getting Scan results back with details of issues in the Base / OS.
Just what I wanted.
