### ISSUE TITLE
eBPF tracking is sometimes disabled

### ISSUE THREAD

**Issue by noboruma** [deepfence/ThreatMapper#269]
**Describe the bug**
When starting probe, we sometimes get this message:
```
<probe> WARN: 2022/01/25 15:03:36.666483 Error setting up the eBPF tracker, falling back to proc scanning: cannot write "p:ptcp_v4_connect tcp_v4_connect\n" to kprobe_events: write /sys/kernel/debug/tracing/kprobe_events: file exists
```

**To Reproduce**
1. Start the agent
2. Kill it abruptly with a `SIGTERM`
3. Start the agent again

**Expected behavior**
eBPF tracking should be starting

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [x] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by noboruma** [comment]
Fix for enabling eBPF tracker even if the entry is already present: c90f416

**Comment by ibreakthecloud** [comment]
Closing this, reopen if required.
