### ISSUE TITLE
Add severity type as a fail parameter in CI/CD integrations

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#275]
- Users can stop a CI/CD build in case the vulnerabilities in the image exceeds certain conditions
- We currently have these conditions
```
fail_cve_count = -1
fail_cve_score = 8
```
- We need to add severity type as a parameter. For example, the following configuration will stop the build in case there is at least 1 critical or at least 5 high or 10 medium or 20 low vulnerabilities
```
fail_cve_count = -1
fail_cve_score = -1
fail_critical_cve_count = 1
fail_high_cve_count = 5
fail_medium_cve_count = 10
fail_low_cve_count = 20
```

**Comment by sidd0529** [comment]
Branches with changes:
  - ThreatMapper: [issue275-severity-type-parameter-cicd](https://github.com/deepfence/ThreatMapper/tree/issue275-severity-type-parameter-cicd)
  - package-scanner: [issue275-severity-type-parameter-cicd](https://github.com/deepfence/package-scanner/tree/issue275-severity-type-parameter-cicd)
