### ISSUE TITLE
Vulnerability scan - error starting the vulnerability mapper container

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#284]
```
docker: Error response from daemon: error while creating mount source path '/var/lib/containerd': mkdir /var/lib/containerd: read-only file system.
```

**Comment by zaka-invozone** [comment]
@ramanan-ravi any update on this?

**Comment by mukuldeepfence** [comment]
Hi @zaka-invozone may I know what permission system you are using for volume mount for `/var/lib/containerd`

so the mode is **read-only** or **read-write**

Reference can be found here - https://github.com/deepfence/ThreatMapper/blob/master/deepfence_backend/tasks/vulnerability_scan_worker.py#L97-L103

**Comment by zaka-invozone** [comment]
I am using the docker-compose file shared in the documentation.

**Comment by mukuldeepfence** [comment]
Please upgrade your setup/console to our latest version
