### ISSUE TITLE
jenkins  cicd  error

### ISSUE THREAD

**Issue by peishunwu** [deepfence/ThreatMapper#285]
+ docker run -d -it '--net=host' -v /var/run/docker.sock:/var/run/docker.sock deepfenceio/deepfence_vulnerability_mapper_ce:latest '-mgmt-console-url=xx.xx.xx.xx:443' '-image-name=deepfenceio/deepfence_vulnerability_mapper_ce:latest' '-fail-cve-count=2' '-fail-cve-score=2' '-mask-cve-ids='
[Pipeline] dockerFingerprintRun
[Pipeline] sh
+ docker logs -f 5431ff364997a7cf2f4ece06dc3f6aef8a4f370ea38eee566a023acb66abe5c5
[36mINFO[0m[2022-02-24 03:16:38] trying to connect to endpoint 'unix:///var/run/docker.sock' with timeout '10s' 
[36mINFO[0m[2022-02-24 03:16:38] connected successfully using endpoint: unix:///var/run/docker.sock 
[36mINFO[0m[2022-02-24 03:16:38] trying to connect to endpoint 'unix:///run/containerd/containerd.sock' with timeout '10s' 
[33mWARN[0m[2022-02-24 03:16:48] could not connect to endpoint 'unix:///run/containerd/containerd.sock': context deadline exceeded 
[36mINFO[0m[2022-02-24 03:16:48] trying to connect to endpoint 'unix:///run/k3s/containerd/containerd.sock' with timeout '10s' 
[33mWARN[0m[2022-02-24 03:16:58] could not connect to endpoint 'unix:///run/k3s/containerd/containerd.sock': context deadline exceeded

![image](https://user-images.githubusercontent.com/14286223/155452608-9a9f131b-f7f5-4648-91cb-d9e036c641a6.png)

**Comment by ibreakthecloud** [comment]
cannot be reproduced
