### ISSUE TITLE
[Update] End User Licence Agreement on ThreatMapper

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#298]
1. Please update the EULA text
![image](https://user-images.githubusercontent.com/34362153/156509141-0d38973b-6551-4951-aac3-93d0f935d151.png)

![image](https://user-images.githubusercontent.com/34362153/156509183-06852992-153a-4387-8255-bd42ff36298d.png)

**Comment by saiprasanth1303** [comment]
The EULA API is returning a 404 error. Fixing that should solve this issue

**Comment by jo19in1** [comment]
Lookig good

![Uploading image.png…]()
