### ISSUE TITLE
Agent can't connect when server behind reverse proxy with letsencrypt/zerossl certificate

### ISSUE THREAD

**Issue by rucciva** [deepfence/ThreatMapper#305]
**Describe the bug**
Even though Management Console's web interface is accessible through the reverse proxy, the connection from agent somehow fail. If reverse proxy is removed, the agent can successfully connect to Management Console

**To Reproduce**
1. Put deepfence management console behind reverse proxy with letsencrypt/zerossl certificate, e.g. caddy
2. Set MGMT_CONSOLE_URL on agent to the reverse proxy domain
4. See error on `/var/log/fenced/discovery.logfile`

**Expected behavior**
Agent successfully connected to management console

**Screenshots**

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [x] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**
Logs (domain and IP redacted): 
```
<probe> INFO: 2022/03/05 05:34:21.022186 command line args: --mode=probe --no-app=true --probe-only=true --probe.cri=false --probe.docker=true --probe.docker.interval=10s --probe.endpoint.report=true --probe.insecure=true --probe.log.level=info --probe.processes=true --probe.publish.interval=10s --probe.spy.interval=5s --probe.token=<elided> --weave=false https://fqdn.tld:443
<probe> INFO: 2022/03/05 05:34:21.022247 probe starting, version 508611f, ID 112676609cd7d34
<probe> ERRO: 2022/03/05 05:34:21.220243 Error fetching app details: Get "https://1.2.3.4:443/topology-api": remote error: tls: internal error
```

**Comment by shyam-dev** [comment]
Does the reverse proxy also handle ssl connections ?

The agent communicates with the management console using certificates on a
secure channel.

The message "remote error: tls: internal error" seems to indicate that the
reverse proxy is unable to handle ssl connections

Thanks
Shyam

**Comment by rucciva** [comment]
> Does the reverse proxy also handle ssl connections ?

Yes it does

> The message "remote error: tls: internal error" seems to indicate that the
reverse proxy is unable to handle ssl connections

But i have no problem accessing the management console (behind the reverse proxy) from the browser.

**Comment by rucciva** [comment]
Here is the snippet from the reverse proxy configuration (caddy v2),

```
<fqdn.tld> {
   tls {
      dns cloudflare {env.CLOUDFLARE_AUTH_TOKEN}
   }
   reverse_proxy <mgmt console ip>:9443 {
      transport http {
          tls_insecure_skip_verify
      }   
   }
}
```

**Comment by ramanan-ravi** [comment]
This issue was fixed in the recent release. Please upgrade to `v1.3.1`.
