### ISSUE TITLE
Cannot compose the docker yaml file

### ISSUE THREAD

**Issue by goyalvartul** [deepfence/ThreatMapper#31]
root@ubuntu-s-6vcpu-16gb-nyc1-01:~# sudo docker-compose -f ./docker-compose.yml up -d
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "././docker-compose.yml", line 119, column 73

**Comment by shyam-dev** [comment]
Hello @goyalvartul 

Can you please ensure that you are using docker-compose version 1.20.1 ?

Also, the error message seems to indicate that there are some extra spaces in your docker-compose file. Can you try to download the file again from the repository and check ?

Thanks

**Comment by goyalvartul** [comment]
Issue is resolved now. I downloaded the whole file using wget. Sorry for
inconvenience
