### ISSUE TITLE
Can Multiple AWS Agents deployed and visible in single management console?

### ISSUE THREAD

**Issue by goyalvartul** [deepfence/ThreatMapper#32]
Can Multiple AWS Agents deployed and visible in single management console?

**Comment by goyalvartul** [comment]
I deployed in two machines as management console, one is in local and another is in cloud machine, it has been running since 2 hours but there is no output

**Comment by shyam-dev** [comment]
Hello @goyalvartul;

As described in the instructions, you can run agents on various AWS systems and point it to the management console. You do not need to have two management consoles.

For example, as outlined [here](https://github.com/deepfence/ThreatMapper#deepfence-agent-on-standalone-vm-or-host), you can run a copy of deepfence agent on any system and point it to the Management Console. Please note that as specified [here](https://github.com/deepfence/ThreatMapper#pre-requisities), the agents need to be able to communicate with the Management console on a specific set of ports.

**Comment by shyam-dev** [comment]
Closing this due to no feedback received
