### ISSUE TITLE
[Vulnerability Scan] [CVE  scan json] no CVSS score, attack vector and fixed versions

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#325]
1.  Scan any container on a VM, in this case Tomcat container
2.  Got to the Vulnerability scans and click on the tomcat:latest container image
![image](https://user-images.githubusercontent.com/34362153/157590204-ad418582-6a13-494a-a21b-c5b80a93a930.png)

3. Click on one of the CVE line items, in this case
![image](https://user-images.githubusercontent.com/34362153/157590389-2d89d7c5-cbd3-48ec-8473-d8f19ea94610.png)

4. The CVSs score is 0 here, the fixed version and the attack vector also is absent
5. But is available on NVD

![image](https://user-images.githubusercontent.com/34362153/157590575-7592ca2c-88e3-4e2b-8837-711018651092.png)

**Comment by ibreakthecloud** [comment]
Has been fixed in new vulnerability flow, pls. reopen if issue re-occurs
