### ISSUE TITLE
Agent and Management are at same IP? Would it show results?

### ISSUE THREAD

**Issue by goyalvartul** [deepfence/ThreatMapper#33]
Agent and Management are at same IP? Would it show results?

**Comment by shyam-dev** [comment]
Hello @goyalvartul;

Yes, you can run vulnerability scans if agent and management console are on the same system. You will be able to see the results.

**Comment by goyalvartul** [comment]
Problem, is that this is scrolling for 2 hours and not showing any data.
Please check the screenshot.

**Comment by sandman137** [comment]
Please join on slack here to discuss thanks
https://join.slack.com/t/deepfence-community/shared_invite/zt-exqn0n82-2lvZLZmlPAiwsW9_JcUUyA

**Comment by shyam-dev** [comment]
Hello @goyalvartul  - We recommend you to try out this use case on the recently released ThreatMapper 1.4.1 and let us know if you have any additional questions. Thank you
