### ISSUE TITLE
[Vulnerability scan][Containers in Kubernetes cluster] scans fail

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#335]
1. Go to the topology page 
2. Select any node from a gke container.
3. Click on "gke-metrics-agent-p6vz2" container
4. Now start a vulnerability scan

![image](https://user-images.githubusercontent.com/34362153/157667724-263d737d-805c-4644-ba4e-888b2bc7edfa.png)

![image](https://user-images.githubusercontent.com/34362153/157667847-8bb724bc-deb6-4b4f-95bb-ec491c11a575.png)

5. Scans will fail with the following error
![image](https://user-images.githubusercontent.com/34362153/157667939-a877b595-3ae6-4b7b-abbf-091087cc50ad.png)

**Comment by saurabh2253** [comment]
kube system containers like gke-metrics cannot be scanned
