### ISSUE TITLE
[K8s console] [vulnerability scan] scan failures

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#340]
1. Setup a K8s cluster. Install management console on it.
2. Connect a regular vm agent. In this setup there is just one fsharp docker container running on the vm.
3. Scan both the fsharp container and the vm. Both scans run forever. 
![image](https://user-images.githubusercontent.com/34362153/158236424-85de6847-fff8-424e-b139-427024e1582d.png)

**Comment by jo19in1** [comment]
This is  still an issue on some docker images pull from docker registries. @jatin-baweja 

![image](https://user-images.githubusercontent.com/34362153/159628326-8e48ac15-d479-4ff6-a215-e7f75505765f.png)

**Comment by FredericoPAlmeida** [comment]
I'm having the same issue. The vulnerability scan run forever.

**Comment by infrapitech** [comment]
Same here, both scans fail when I launch them.

**Comment by ibreakthecloud** [comment]
this might be similar to : https://github.com/deepfence/ThreatMapper/issues/469

@jo19in1 pls. confirm

**Comment by jo19in1** [comment]
Similar issue. Its already fixed.
