### ISSUE TITLE
[K8s console] console node does not appear on UI

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#341]
1. Set up a 3 node cluster management cluster
2. Load the console on a browser. Look at the topology
3. The nodes do not show up on the UI
4. Only region is visible
![image](https://user-images.githubusercontent.com/34362153/158239028-7a4f5f58-9dd6-47ad-8e67-edb2224950bb.png)

5. Discovey logs

```
<probe> ERRO: 2022/03/14 16:31:13.409740 docker registry: Get "http://unix.sock/containers/json?all=1": dial unix /var/run/docker.sock: connect: no such file or directory
<probe> ERRO: 2022/03/14 16:31:23.411003 docker registry: Get "http://unix.sock/containers/json?all=1": dial unix /var/run/docker.sock: connect: no such file or directory
<probe> ERRO: 2022/03/14 16:31:33.412227 docker registry: Get "http://unix.sock/containers/json?all=1": dial unix /var/run/docker.sock: connect: no such file or directory
```

**Comment by saurabh2253** [comment]
In the values.yaml please set the dockerSock flag as false and redeploy

**Comment by jo19in1** [comment]
Ok, users may not be aware of such minor configurations as they might use DO, aws or other cloud providers
 It should be an automated.
