### ISSUE TITLE
[Runtime bom] not getting displayed on UI

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#343]
1. Setup:  k8s console, regular vm agent or regular vm agent and console
2. 
![image](https://user-images.githubusercontent.com/34362153/158331259-de9b79f4-c57e-481a-b7bf-a90b9e3942bb.png)

**Comment by jo19in1** [comment]
This is happening on certain containers like tomcat right now

**Comment by jo19in1** [comment]
Looking good now

**Comment by jo19in1** [comment]
Issue happening again on 1.3.0

![image](https://user-images.githubusercontent.com/34362153/159628930-1d40228f-33d7-4412-b2a1-dc2447a3fa55.png)

**Comment by shyam-dev** [comment]
Please check if the 1.3.0 image that you use is the latest from dockerhub
