### ISSUE TITLE
[Vulnerability & Secret Management] deletion of scan results resets scan status

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#356]
**Describe the bug**
When a user deletes vulnerabilities and/or secret scan results, only the scan results are to be deleted, scan statuses must remain unchanged.

**To Reproduce**
1. Go to registries page and add a registry such as plone. 
2.  Select all the images in that registry and scan all images for vulnerability
3.  Now go to settings--> Vulnerability & Secret Management and delete all vulnerability and secret scans.
4. Now go back to the registres page and check the statuses of all scans.
5.  The statuses are all reset to 'Never Scanned'. But in reality, the scans are in progress and they will complete as their turn comes uo in the queue

**Screenshots**
![image](https://user-images.githubusercontent.com/34362153/159407558-07fa988a-9cb2-4844-a1f9-d6102ee8a2c0.png)
**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by shyam-dev** [comment]
This is correct behavior. If scan results are dropped from management console, so should the status. If the status is not reset, then we will not be able to show the results.

Closing this issue
