### ISSUE TITLE
[Toplogy node expansion] sporadic issues

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#363]
**Describe the bug**
I am unable to expand the console node at times.

**To Reproduce**
1. Go to 'topology and click on the Digitialocean node, it will expand to the console vm  and so on.
2. In this situation I downloaded a pdf report, and then when I went to the topology page, cannot seem to expand beyond the DO node
3. api container logs
![image](https://user-images.githubusercontent.com/34362153/160544894-ca761d4d-d726-4874-8219-184f9d72b745.png)

4. Browser Console error
![image](https://user-images.githubusercontent.com/34362153/160545250-4b91be0c-13e7-4a5a-8f21-b9b3a5385d11.png)

**Expected behavior**
Every node must recursively expand till the terminal node on clicking 

**Screenshots**

![image](https://user-images.githubusercontent.com/34362153/160544732-3d0f7cc4-05fa-4a1d-ad8e-ca5078b6ac77.png)

**Components/Services affected**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ibreakthecloud** [comment]
@manV is this fixed?

**Comment by manV** [comment]
not reproducible. we can probably close this.
