### ISSUE TITLE
Enhance the vulnerability database

### ISSUE THREAD

**Issue by shyam-dev** [deepfence/ThreatMapper#367]
**Additional context**
Enhancements to the vulnerability database to add additional sources

**Is your feature request related to a problem? Please describe.**
Certain vulnerabilities are being missed out because they are found in sources which are not being used

**Describe the solution you'd like**
While the current vulnerability database is quite comprehensive, we should enhance the database with feeds from other sources. One such example is the gitlab advisory database.

**Components/Services**

- [ ] UI/Frontend
- [X] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by sandman137** [comment]
Can we publish list of current feeds and the ones we are planning to add? Also I think we should the vulnerability db available as part of release pkgs here in GitHub every 6 hours.
