### ISSUE TITLE
How to modify admin user or create other one.

### ISSUE THREAD

**Issue by adesito** [deepfence/ThreatMapper#37]
Intalled deepfence and create the first registration... with an error in the email. Try to change but it doesn't have any button to modify only delete but if you try to delete admin you cant do that. If I want to create other admin user is not possible or tranfers de admin role to other user is not possible.

**Comment by sandman137** [comment]
Hi, can you please join us on slack so we can help you debug this closely. 

https://join.slack.com/t/deepfence-community/shared_invite/zt-exqn0n82-2lvZLZmlPAiwsW9_JcUUyA

**Comment by sandman137** [comment]
Overall, broader user management and roles is not part of the community edition yet, we will bring it here soon. Having said that, can we take a look at the error that you are seeing?

**Comment by adesito** [comment]
Sorry for the delay. I write a wrong email for the admin user and now I don't know how to change that email or if its possible to change.

**Comment by ramanan-ravi** [comment]
@adesito You can clear the user database by running following commands.
- Remove all containers
```
docker-compose -f docker-compose.yml down
```
- Delete deepfence docker volume
```
docker volume rm $(docker volume ls | grep deepfence | awk '{print $2}')
```
- Start all containers
```
docker-compose -f docker-compose.yml up -d
```
- You can register with correct email id now.

**Comment by shyam-dev** [comment]
Hello @adesito  - You cannot change the email id of the admin user. You can however create a new admin user, delete the existing user and add the correct user with the correct email id again. Please check this out on ThreatMapper 1.4.1 that was released recently and let us know if this meets your requirement
