### ISSUE TITLE
Change Router to support Env Variables for service addesses

### ISSUE THREAD

**Issue by wkleinhenz** [deepfence/ThreatMapper#371]
**Additional context**
When deploying the router container, it uses hard coded addresses both to check if the API is running and for the HAproxy config to route to back-end services, Ideally this should use environment variables so that these options can be configured dynamically to allow for more complicated deployments

**Is your feature request related to a problem? Please describe.**
My main use case for the time being is using nomad along with consul connect which allows for services in the larger cluster to be presented over 127.0.0.1 and some definable port, it however does not as far as I know allow me to define the container name when using the standard bridge networking.

**Describe the solution you'd like**

The check to see if the deepfence-api:9997 address is reachable could use something similar to API_HOST and API_PORT, along with the similar env vars being used to set server values in the haproxy config. It appears that both of these files already include some level of env var usage so expanding the available variables might be pretty straight forward.

**Describe alternatives you've considered**
It would be possible to replace the existing entrypoint and haproxy.cfg file with versions that allow for this, but this adds additional complexity mainly revolving around the maintaining of these files on the users end

**Components/Services**

- [X ] UI/Frontend
- [X ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**
It seems like there may be some other instances of hardcoded address names, i noticed that deepfence-api and some other service/container names are also hard coded in some other locations and it might be best to convert those if possible too

**Comment by wkleinhenz** [comment]
Ive included a scrubbed nomad config [here](https://gist.github.com/wkleinhenz/2c8305f464b6813f58260c61c4ceb705), let me know if theres any questions I should be reachable via notifications here and also in the slack user group

**Comment by ramanan-ravi** [comment]
Hello Dave,

Please download and install the deepfence-console helm chart from [here](https://drive.google.com/file/d/1ZQSknBVzHMXmeUuqUEHeooIzmP-5jKh2/view?usp=sharing).

**First try redeploying the helm chart**
```
helm delete deepfence-console
cd /path/to/console-helm-chart
helm install deepfence-console ./
```
**If postgresql still doesn't work:**

helm delete deepfence-console
kubectl delete pvc <>
kubectl delete pv <>

Setup RDS postgresql version 12.x

**Comment by gnmahanth** [comment]
@wkleinhenz we have recently updated haproxy config to take service host and port from environment variables, you can check and build code from master branch

**Comment by wkleinhenz** [comment]
Great thanks for adding this, ill close this as being completed
