### ISSUE TITLE
Elasticsearch mapper_parsing_exception for sbom-artifact

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#403]
Fetcher logs
```
Error Type:mapper_parsing_exception
Error Reason: failed to parse
sbom-artifact
status:400
```

**Comment by saurabh2253** [comment]
happening for any particular image?

**Comment by saurabh2253** [comment]
Observation: Did a docker volume prune (fresh install), I could see the error when items on sbom-artifact is getting published. Image scanned was convertigo:latest. Not all item publishes are failing as I could see the results in Runtime BOM
