### ISSUE TITLE
Number of Containers and Container Images are not populating in Console.

### ISSUE THREAD

**Issue by zanilgupta** [deepfence/ThreatMapper#406]
**Describe the bug**
After installation of an agent on k8s cluster, Cluster,pods, Namespaces and host show up in the console(hosted on AWS ec2 using docker-compose) but Containers and Container Images shows zero
**To Reproduce**
Install the agent and console does not show number of  Containers and Container Images it always shows "0"

**Expected behavior**
show the number of  Containers and Container Images

**Screenshots**
Attached
**Components/Services affected**

- [ ] UI/Frontend

**Additional context**
![Screen Shot 2022-04-18 at 10 30 20 AM](https://user-images.githubusercontent.com/99214813/163849014-4dc92f72-e05a-42ef-ac69-34a6b7525647.png)

**Comment by zanilgupta** [comment]
The console ec2 configurations are
m4.2xlarge(8cpu and 32)

**Comment by zanilgupta** [comment]
Diagnostic logs are attached in the Slack thread: https://deepfence-community.slack.com/files/U039ANX972B/F03BTLTLVSR/deepfence-logs.tgz

**Comment by sandman137** [comment]
I think this is sorted out now @zanilgupta
