### ISSUE TITLE
Support custom ca's in registry integration

### ISSUE THREAD

**Issue by JannikJ** [deepfence/ThreatMapper#415]
**Is your feature request related to a problem? Please describe.**
When connecting to private registries with a custom certificate authority, an SSLCertVerificationError occurs

**Describe the solution you'd like**
Importing a custom certificate authority should be supported.

**Describe alternatives you've considered**
Alternatively, an option to ignore all problems with certificates when connecting to an image registry, could be implemented.

**Components/Services**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by ramanan-ravi** [comment]
@JannikJ Which registry are you setting up?

**Comment by JannikJ** [comment]
I'm using Harbor but glancing over the code, I guess there is no big difference between the registries? When trying to connect, it shows the error from [cve_scan_registry/scan_registry/cve_scan_registry.py#L696](https://github.com/deepfence/ThreatMapper/blob/9c9bd2e757519ba3ff34941f4112869df7ba5a87/deepfence_backend/cve_scan_registry/scan_registry/cve_scan_registry.py#L696])

**Comment by ramanan-ravi** [comment]
We do support self signed certificates and custom CA for Harbor.
Can you follow this?

>Using Certificate based Docker client Authentication?
A custom certificate is configured by creating a directory under /etc/docker/certs.d on Deepfence console machine, using the same name as the registry's hostname provided above. All *.crt files are added to this directory as CA roots.
https://docs.docker.com/engine/security/certificates/

**Comment by JannikJ** [comment]
I see, thank you! This works for me.
