### ISSUE TITLE
Issue scanning Management node and registries 

### ISSUE THREAD

**Issue by jrose1738** [deepfence/ThreatMapper#42]
Unable to run vulnerability scans on management console node and registries. Vulnerability scans start but hang after a while with error "Scan was interrupted".  There is no info in the docker-compose logs to investigate or viewable logs from the console itself.

**Comment by sandman137** [comment]
Are you trying to scan containers and hosts on which console is deployed?

**Comment by jrose1738** [comment]
Yes, there is an agent deployed on the host on which the console is deployed.

**Comment by mukuldeepfence** [comment]
Can you please join here, so that we can take a closer look at it?
https://join.slack.com/t/deepfence-community/shared_invite/zt-iicjmffl-8G2hY74AyKv9v4xHwfJ~3g

**Comment by jrose1738** [comment]
I am unable to join the slack channel due to not having a deepfence email

**Comment by shyam-dev** [comment]
Hello;

Try to join using this link
https://join.slack.com/t/deepfence-community/shared_invite/zt-jm9amh4z-o~S6_jnrHXijR01N25gPyw

Thanks
Shyam

**Comment by shyam-dev** [comment]
Hello @jrose1738 - Quick update post our discussion. We should have a solution for you by Friday morning EDT.

**Comment by shyam-dev** [comment]
Hello @jrose1738 - We have updated the images in the dockerhub repository. Please download it and try it out. It should fix the issue.

Thanks !
