### ISSUE TITLE
log4j-core vulnerabilities being detected is a false positive.

### ISSUE THREAD

**Issue by ak12021996** [deepfence/ThreatMapper#450]
We found this log4j vulnerabilities in 'deepfenceio/deepfence_elastic_ce'  if log4j issue is already resolved in 1.3.0 release, why deepfence console is still flagging it.
As per slack conversation log4j-core vulnerabilities being detected is a false positive. Since the elasticsearch didn't send the patch for the elasticsearch-oss-no-jdk. So team already removed the vulnerable class(JndiLookup.class) from the jar, so the final image does not have log4j related vulnerabilities but still deepfence console is flagging it. Team is working on getting false-positive fixed.
Raising this issue to keep track on progress.
![8819f831-d355-45ad-9622-01df260bb6c4 (1)](https://user-images.githubusercontent.com/105700358/170647913-481474c0-64ee-4a8f-930b-a2b55e0b1336.PNG)

**Comment by ibreakthecloud** [comment]
@sidd0529 would verify if we still getting the false positives?

**Comment by ibreakthecloud** [comment]
has been fixed
