### ISSUE TITLE
Console Not Available

### ISSUE THREAD

**Issue by kentsaunders** [deepfence/ThreatMapper#462]
I have deployed ThreatMapper using "docker-compose -f docker-compose.yml up -d".  

- The containers start and netstat reveals the docker-proxy process on the host is listening on 0.0.0.0:443.  
- "docker container ls" shows "deepfenceio/deepfence_router_ce:1.3.1 " running and 0.0.0.0:443->443/tcp
- When I open bash on the container I am able to open port 443 using "nc -l -p 443" without an error - which tells me no other process is using that port.  When I open the port on the container using nc,  I am able to connect from my workstation using the "test-netconnection" powershell command.
- I have tried on RHEL 7.9 and Ubuntu 20.04 with the same result.

Docker-ce was installed from the latest binaries - https://download.docker.com/linux/static/stable/x86_64/docker-20.10.9.tgz

**Comment by ibreakthecloud** [comment]
@kentsaunders can you post the output of `docker-compose -f docker-compose.yml ps` ?

**Comment by kentsaunders** [comment]
[root@ip-10-100-44-78 ec2-user]# docker-compose -f docker-compose.yml ps
NAME                             COMMAND                  SERVICE                          STATUS              PORTS
deepfence-api                    "/app/code/dockerify…"   deepfence-api                    running
deepfence-backend                "/app/code/dockerify…"   deepfence-backend                running
deepfence-celery                 "/app/code/dockerify…"   deepfence-celery                 running
deepfence-console-agent          "/usr/local/bin/star…"   deepfence-console-agent          running
deepfence-diagnosis              "/home/diagnosis"        deepfence-diagnosis              running
deepfence-es-master              "/usr/bin/startEs.sh…"   deepfence-es                     running             127.0.0.1:9200->9200/tcp, 127.0.0.1:9300->9300/tcp
deepfence-fetcher                "/usr/bin/start_fetc…"   deepfence-fetcher                running             8006/tcp
deepfence-internal-router        "docker-entrypoint.s…"   deepfence-internal-router        running             127.0.0.1:8443->443/tcp
deepfence-package-scanner        "/usr/local/bin/pack…"   deepfence-package-scanner        running             8005/tcp
deepfence-postgres               "docker-entrypoint.s…"   deepfence-postgres               running             5432/tcp
deepfence-redis                  "/usr/local/bin/star…"   deepfence-redis                  running             6379/tcp
deepfence-router                 "docker-entrypoint.s…"   deepfence-router                 running             0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, :::80->80/tcp, :::443->443/tcp
deepfence-secret-scanner         "/home/deepfence/usr…"   deepfence-secret-scanner         running
deepfence-topology               "/home/deepfence/ent…"   deepfence-topology               running             127.0.0.1:8004->8004/tcp
deepfence-ui                     "/home/deepfence/ent…"   deepfence-ui                     running
deepfence-vulnerability-mapper   "/entrypoint.sh"         deepfence-vulnerability-mapper   running             8001/tcp
df-init-container                "/usr/local/bin/entr…"   deepfence-init-container         exited (0)

**Comment by shahpratikr** [comment]
Issue was with elastic container as it was failing to start any process because vm.max_map_count was set less than 262144.
