### ISSUE TITLE
K8s cluster count/Pods/Namespace is missing or showing zero

### ISSUE THREAD

**Issue by zanilgupta** [deepfence/ThreatMapper#472]
**Describe the bug**
I have installed  console on ec2 with 16 core and 64 GB memory. After installing agent EKS clusters
K8s cluster count/Pods/Namespace is missing or showing zero
But inside host I can see all the EKS nodes

**Expected behavior**
Its should show correct no of eks cluster/pods and Namespaces
**Screenshots**

**Components/Services affected**

- [ ] UI/Frontend

**Additional context**
![Screen Shot 2022-06-21 at 9 55 18 AM](https://user-images.githubusercontent.com/99214813/175392294-38c142f7-ff2e-4ebd-860e-62d5c8e92488.png)

**Comment by saurabh2253** [comment]
@zanilgupta Was the cluster showing up in K8s view on the topology view in screenshot. If not can you please attach agent logs from /var/log/fenced/discovery.logfile in agent pod

**Comment by saurabh2253** [comment]
Closing as this has been inactive for over a month.
