### ISSUE TITLE
Output of secret scanner has mount paths of the actual host files used

### ISSUE THREAD

**Issue by shyam-dev** [deepfence/ThreatMapper#507]
**Describe the bug**
The output of the secret scanner has mount paths of actual host files

**To Reproduce**
The host filesystem is mounted into /tmp/Deepfence for scanning purposed. The output json of the secret scanner should not show that mountpath

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by saurabh2253** [comment]
This is working as expected on our internal setup. @ramanan-ravi Can we please have the logs from system where this error occurred.
