### ISSUE TITLE
PDF report always shows "No vulnerabilities found for the applied filters"

### ISSUE THREAD

**Issue by mustajarvi** [deepfence/ThreatMapper#526]
Thanks for providing this tool!

**Describe the bug**
When trying to generate a PDF report with vulnerabilities a PDF with the text "No vulnerabilities found for the applied filters" is always generated. Switching to the XLSX format returns thousands.

**To Reproduce**
1. Go to 'Integrations > Reports / PDF/XLSX'
2. Select 'Vulnerabilities', 'container image', 'last 1 day' and PDF format.
3. Click Download.
4. Wait until report is generated and download it (a file without vulnerabilities is generated).
5. Switch to XLSX download type and click Download.
6. A XLSX file with thousand of vulnerabilities is shown.

**Expected behavior**
I expected that the only difference would be the file format. The list of vulnerabilities should be the same.

**Screenshots**
Filter settings and "Filters used" - Note the differences here.
![image](https://user-images.githubusercontent.com/1049525/184881315-3210f690-8ca2-460c-a6f3-039e4c31071c.png)

Extract from XLSX:
![image](https://user-images.githubusercontent.com/1049525/184881629-e509e4cd-c5c3-4f84-a528-437ddb7a0ced.png)

PDF file downloaded:
![image](https://user-images.githubusercontent.com/1049525/184881790-8bab3dc8-b232-4f80-b52a-4c744d996997.png)

**Components/Services affected**

Making a best effort guess here.

- [X] UI/Frontend
- [X] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

I hope the above helps with tracking down the issue. Since the Filters Used are different depending on file format, I suspect the issue might lay there.

Thanks

**Comment by mukuldeepfence** [comment]
Hi @mustajarvi , can you please post the diagnosis logs ?
If you have scanned the image from the agent in this case please post the logs of the agents as well


**Diagnosis logs** can be found at Settings -> Diagnosis

**Comment by mustajarvi** [comment]
Sure. Attaching the diagnosis logs. Note that the logs are from today, while the screenshots above are from a week ago.

[deepfence-logs.tar.gz](https://github.com/deepfence/ThreatMapper/files/9394634/deepfence-logs.tar.gz)

(Had to rename the file ending from .tgz to .tar.gz )

The scan was done by the deepfence package scanner.

**Comment by ibreakthecloud** [comment]
@mukuldeepfence did find any issues here ?

**Comment by ibreakthecloud** [comment]
Just confirmed with @mukuldeepfence , the issue was with XLSX reporting. The pdf report for the applied filter was correct. This issue has been resolved in `master` and will be available on next releases or patch.

**Comment by shyam-dev** [comment]
Hello @mustajarvi  - There was an issue with applying filters, which has been fixed in the recently released 1.4.1 version of Threatmapper. Request you to please check if you still see the issue. Thank you

**Comment by mustajarvi** [comment]
Hello @shyam-dev - I am able to download the report I needed now. Thank you!
