### ISSUE TITLE
Upload Vulnerabilty Database Issue

### ISSUE THREAD

**Issue by wonhee0410** [deepfence/ThreatMapper#557]
**Describe the bug:**
Cannot upload the vulnerability database.

**To Reproduce:**
1. Go to Settings > Vulnerability & Secret Management
2. Upload the vulnerability database with tar.gz file
3. Check Network tab on browser, it shows POST 404 Not Found with this URL: https://address/undefined/df-api/upload-vulnerability-db

**Screenshots:**
![Screenshot 2022-09-13 091852](https://user-images.githubusercontent.com/60768442/189793364-d2ea93d8-5328-45a8-8c54-f23ce7e0e0a3.png)

**Additional context:**
Deepfence: 1.4.0

**Comment by shyam-dev** [comment]
Hello @wonhee0410  - This issue has been fixed in the recently release 1.4.1 version of ThreatMapper. Request you to kindly check it out and let us know if you still see the issue. Thank you

**Comment by huydq2vietcapitalbank** [comment]
> Hello @wonhee0410 - This issue has been fixed in the recently release 1.4.1 version of ThreatMapper. Request you to kindly check it out and let us know if you still see the issue. Thank you

Hi @shyam-dev, I have tested the function, but it shows this error.
![image](https://user-images.githubusercontent.com/111732485/193516195-3dc8524f-51f0-4e0b-8045-a7c0c45dc2bf.png)

**Comment by ramanan-ravi** [comment]
@manV Can you add loading gif and response in the UI?

**Comment by huydq2vietcapitalbank** [comment]
> @manV Can you add loading gif and response in the UI?

Sorry for the inconvenience, I will describe the response in UI.

- When I click the Upload button, there is no loading cursor, no browser loading or something like that.

- After about 5 seconds, I see in the network tab, it shows errors like this.

![image](https://user-images.githubusercontent.com/111732485/193716161-7b6d895a-6b9c-4741-a386-9aa4ecbb397a.png)

- And the UI is still the same as before I clicked the Upload button, no responding.

![image](https://user-images.githubusercontent.com/111732485/193716271-fef342aa-2db4-4264-9c9e-c123c0495f45.png)

Thank you.

**Comment by ibreakthecloud** [comment]
Hi @huydq2vietcapitalbank are you using the latest release or have you built from the source?

**Comment by wonhee0410** [comment]
> Hi @huydq2vietcapitalbank are you using the latest release or have you built from the source?

I'm using latest release (Docker installation) with the commands from your document.
```
wget https://github.com/deepfence/ThreatMapper/raw/release-1.4/deployment-scripts/docker-compose.yml
env DF_IMG_TAG=1.4.1 docker-compose -f docker-compose.yml up -d
```

**Comment by ibreakthecloud** [comment]
> > Hi @huydq2vietcapitalbank are you using the latest release or have you built from the source?
> 
> I'm using latest release (Docker installation) with the commands from your document.
> 
> ```
> wget https://github.com/deepfence/ThreatMapper/raw/release-1.4/deployment-scripts/docker-compose.yml
> env DF_IMG_TAG=1.4.1 docker-compose -f docker-compose.yml up -d
> ```

can you remove all the images with tag 1.4.1 and then fresh pull it.(running env DF_IMG_TAG=1.4.1 docker-compose -f docker-compose.yml up -d will automatically pull it) ?
Since there were few fixes that was done
