### ISSUE TITLE
UI: remove legacy scope code

### ISSUE THREAD

**Issue by manV** [deepfence/ThreatMapper#59]
**Is your feature request related to a problem? Please describe.**
Currently there are a lot of components using older way of doing things in React, It makes them harder to maintain.

**Describe the solution you'd like**
Going forward and iteratively - so without stopping bug fixes/feature development - we should do the following:

- [ ] Port class based components to functional components. This simplifies the code, and makes it easier to execute the remaining steps
- [ ] Move all the state that is currently stored in redux for no good reason to *local* component state, leaving in redux only the bare minimum (see my recent side panel rewrite)
- [ ] Once most code is self contained (uses local state, doesn't have unnecessary external dependencies anymore, uses component scoped css), transplant the code in a new shell, built with https://astro.build or equivalent. 
- [ ] Get rid of the scope code entirely.

This will allow us to get rid of some really old scope code, speed up builds, make the product faster and generally modernize and make the code base easier to maintain.

**Components/Services**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by ibreakthecloud** [comment]
@manV can this be closed?

**Comment by manV** [comment]
Yes
