### ISSUE TITLE
Remove admin settings like audit logs and diagnosis from non-admin users setting

### ISSUE THREAD

**Issue by manV** [deepfence/ThreatMapper#61]
**Describe the bug**
Audit logs and diagnosis sections are restricted via api to non-admin users, but the sections in the ui are still visible.

**To Reproduce**
1. Log in as non admin user.
2. Go to settings > user audit logs

**Expected behavior**
Admin settings should be hidden for non-admin users

**Screenshots**
<img width="1306" alt="138240784-d73ee400-5266-4e18-87a9-9192eafded72" src="https://user-images.githubusercontent.com/4988376/138314544-ce39c13f-a809-4f47-9f0f-0d4369c8d238.png">

**Components/Services affected**

- [x] UI/Frontend
- [ ] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by ibreakthecloud** [comment]
already removed for non-admin users
