### ISSUE TITLE
Back-end implementation for cleanup Compliance data 

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#650]
Backend implementation in api to clean up data for compliance scans is missing 

api code: https://github.com/deepfence/ThreatMapper/blob/master/deepfence_backend/api/common_api.py#L840

required to fix this issue https://github.com/deepfence/ThreatMapper/issues/646

**Comment by shyam-dev** [comment]
We dont need a separate issue ! Lets use #646 to track !
