### ISSUE TITLE
Doc count is wrong in the posture scans if we delete few docs from the setting page

### ISSUE THREAD

**Issue by mukuldeepfence** [deepfence/ThreatMapper#662]
**Describe the bug**
Doc count is wrong in the posture scans if we delete few docs from the setting page

**To Reproduce**
1. go to the settings and delete info status from the there for the posture scans
2. now see the scan results those are unchanged but docs inside those has been deleted

**Expected behavior**
counts should be same every where

**Screenshots**
![image](https://user-images.githubusercontent.com/72725782/200234280-9d13ab7c-e2ac-490d-88b9-c0f478ea29c4.png)

![image](https://user-images.githubusercontent.com/72725782/200234318-36370e8f-29a2-48a1-9b5a-d0c1b4a7eb21.png)

counts for the scan is different in both images but these should be same
**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Comment by akumars1** [comment]
Still count is showing diff after deleting some info logs 
<img width="1726" alt="Screenshot 2022-12-07 at 6 02 44 PM" src="https://user-images.githubusercontent.com/111341228/206180440-ba1cb9fb-19d1-4c2b-9949-e11896115993.png">

<img width="1728" alt="Screenshot 2022-12-07 at 6 02 11 PM" src="https://user-images.githubusercontent.com/111341228/206180432-ff640f61-833d-4d8e-b1b0-c17aadcca149.png">

**Comment by akumars1** [comment]
Tested & Verified in image kafka-tm
