### ISSUE TITLE
Add option to pass existing tls secret for console in helm-chart

### ISSUE THREAD

**Issue by gnmahanth** [deepfence/ThreatMapper#663]
TLS certs are expected to be inside the helm chart directory when deploying console with custom https certificates.
Add a option in deepfence-console helm chart to pass already existing tls certificates from secrets.

**Comment by lumattr** [comment]
This is also needed for cert-manager support. 👍

**Comment by lumattr** [comment]
@gnmahanth Hi, this implementation doesnt allow for cert-manager support as you need the ability to add a `tls` field the spec of the ingress. Something like the below from the grafana helm chart is how i see it pretty consistently implemented in other major projects:

https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L271-L307
https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml#L30-L33

**Comment by gnmahanth** [comment]
@lumattr this issue belongs to old version of ThreatMapper(version 1), can you check version 2 helm charts from the release, if they don't satisfy your requirement please create a new issue we will update the charts
