### ISSUE TITLE
Console not showing 

### ISSUE THREAD

**Issue by rohan-birtia** [deepfence/ThreatMapper#721]
**Describe the bug**
I am running the Docker environment on an AWS EC2 instance.

**To Reproduce**
1. Followed one by one https://community.deepfence.io/docs/threatmapper/console/docker.

**Screenshots**
<img width="929" alt="image" src="https://user-images.githubusercontent.com/110599270/205268096-d4793dd8-8b6b-461e-a112-01ce0c549f8b.png">

**Components/Services affected**
- UI/Frontend

**Comment by ramanan-ravi** [comment]
Hi @rohan-birtia, can you share the logs of `deepfence-router`?
```
docker logs deepfence-router
```

Can you also share the vm's os (`/etc/os-release`) and config (memory, cpu).

**Comment by rohan-birtia** [comment]
@ramanan-ravi ,
<img width="587" alt="image" src="https://user-images.githubusercontent.com/110599270/205278961-cc06c4fa-dae5-4b09-8435-86c15e0e549e.png">
<img width="310" alt="image" src="https://user-images.githubusercontent.com/110599270/205279091-b7b62d59-6611-482e-8439-870c2f2c2127.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/110599270/205279524-636473ee-d8c3-41c3-af0c-14cf621e3a71.png">
<img width="566" alt="image" src="https://user-images.githubusercontent.com/110599270/205279844-e3ff45a6-c339-4009-ad6b-9a6d1cf438ab.png">

**Comment by ramanan-ravi** [comment]
Few additional steps are required in Amazon linux. Please follow [these](https://docs.deepfence.io/docs/threatmapper/console/troubleshooting#docker-configuration-in-amazon-linux--rhel) to fix the issue.
