### ISSUE TITLE
Postgres Crashing Deployed via Helm

### ISSUE THREAD

**Issue by rohan-birtia** [deepfence/ThreatMapper#722]
**Describe the bug**
Followed all the steps mentioned https://github.com/deepfence/ThreatMapper/tree/master/deployment-scripts/helm-charts/deepfence-console#setup-storage

Installed console via helm chart

**To Reproduce**
1. Helm v3

**Screenshots**
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/110599270/205282502-d89b7881-5786-4f68-916f-ba4854a8860f.png">

**Components/Services affected**
- API/Backend
- -Deployment/YAMLs

**Comment by ibreakthecloud** [comment]
@rohan-birtia does all the pods in running state, and also can you tell about the k8s cluster you are using for it, like version, node count, cloudprovider, etc.?
