### ISSUE TITLE
[BUG] mismatch in the number of containers on the agent vs UI(sidepanel)

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#73]
**Describe the bug**
Difference in the number of docker contaniers  listed inside the console VM vs what is shown on side panel

**To Reproduce**
1. Go to the toplogy page
2. Click on any agent node
3. On the side panel look at the number of images that are listed
example 
![image](https://user-images.githubusercontent.com/34362153/138803480-02e9ea58-9ccb-4940-913a-914617b72a64.png)

4. Now ssh into the agent and issue a "docker image ls" command on the terminal
5. You will see the following output 
![image](https://user-images.githubusercontent.com/34362153/138803669-654333ea-38fc-469f-8444-8ae779a57e81.png)

6. Compare the number of container images that are shown in the terminal vs the ones on the side panel. There is too much difference. About 30 images are missing from the side panel

**Expected behavior**

**Screenshots**

**Components/Services affected**

- [x] UI/Frontend
- [x] API/Backend
- [x] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by mukuldeepfence** [comment]
This is an expected behavior of the scope right now
we will be seeing only those image for those we have container running
