### ISSUE TITLE
[Invitation email], format the invitation email

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#78]
**Describe the bug**
The current invitation email formatted incorrectly

**To Reproduce**
1. Go to Settings-->User management. Send an invite to any of your gmail ids.
2. Go to your inbox and check for invitation email
3. This is how it looks at the moment:
![image](https://user-images.githubusercontent.com/34362153/138917868-807edc84-9af9-4fdf-a7d3-8d02f0891ae3.png)

**Expected behavior**
Dear User,

You've been invited to access the Deepfence dashboard.
Please click on the following link to register. Register

**Screenshots**

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by ibreakthecloud** [comment]
@ramanan-ravi can we close this?
