### ISSUE TITLE
Containers on a node not showing on Console

### ISSUE THREAD

**Issue by geolney** [deepfence/ThreatMapper#783]
**Describe the bug**
On the Deepfence Console, when clicking a Node that a deepfence-agent is running on it doesn't show any of the containers running on it and instead brings up a sidebar (screenshot below).

When getting the discovery.log of the agents it provides continuous lines of:
`<probe> ERRO: 2023/01/05 10:29:46.519696 docker registry: Get "http://unix.sock/containers/json?all=1": dial unix /var/run/docker.sock: connect: no such file or directory`

When exec'ing into the deepfence-agent I can see the variable correctly passed through:
`kubectl exec -it deepfence-agent-ght2d -n threatmapper -- sh
sh-5.1# printenv | grep docker
DOCKER_SOCKET_PATH=/var/run/dockershim.sock`

**To Reproduce**
1. Have a node for your EKS cluster with runtime Docker and docker-sock file as `/var/run/dockershim.sock`
2. Deploy helmChart with the vars `dockerSock: true` , `dockerSockPath: "/var/run/dockershim.sock"` , `containerdSock: false`
3. Wait for agents to spin up and access the console, click on a node
4. See that containers do not show.

**Expected behavior**
When clicking on a node on the console I should be able to see the containers and names that are running on that specific node. 

**Screenshots**
<img width="1045" alt="Screenshot 2023-01-05 at 10 42 11" src="https://user-images.githubusercontent.com/75424289/210761485-9915464c-21e0-4280-9a3a-8c663e4dcebd.png">

Happy to attach more logs/screenshots upon request to assist with this issue.

**Components/Services affected**

- [ ] UI/Frontend
- [ ] API/Backend
- [X] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**
N/A

**Comment by ramanan-ravi** [comment]
Error after [this](https://github.com/deepfence/ThreatMapper/pull/788) change
```
<probe> ERRO: 2023/01/09 15:29:11.493458 docker registry: Get "tcp:///var/run/dockershim.sock/containers/json?all=1": unsupported protocol scheme "tcp"
<probe> ERRO: 2023/01/09 15:29:21.494444 docker registry: Get "tcp:///var/run/dockershim.sock/containers/json?all=1": unsupported protocol scheme "tcp"
<probe> ERRO: 2023/01/09 15:29:31.495479 docker registry: Get "tcp:///var/run/dockershim.sock/containers/json?all=1": unsupported protocol scheme "tcp"
```

**Comment by ramanan-ravi** [comment]
Update: It worked after setting containerRuntime as containerd.
