### ISSUE TITLE
[Integrations] read-only users see a loader icon for integration pages

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#81]
**Describe the bug**
When a read-only user goes to the integrations page, there is an attempt to get existing integrations, but you get a 500 error

**To Reproduce**
1. Invite a ready only user from User Management --> Send Invite
2. Now login as a read-only user
3. Go to the integrations page-->Email/Slack/PagerDuty etc.
4. You will see that /integrations API gives 500 error

**Expected behavior**
Show existing integrations to read-only users also.
But they must not be able to edit them.

**Screenshots**
![image](https://user-images.githubusercontent.com/34362153/138929264-7f037cc8-c885-4509-aabd-2af0ab292be1.png)

**Components/Services affected**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**

**Comment by mukuldeepfence** [comment]
this information is for only account owners so feature is working as expected
