### ISSUE TITLE
ECR scanning takes forever

### ISSUE THREAD

**Issue by shyam-dev** [deepfence/ThreatMapper#911]
**Describe the bug**
Issue described here - https://github.com/deepfence/ThreatMapper/discussions/910

**Comment by shyam-dev** [comment]
Hello @njahrckstr - Will you be able to post the diagnostic logs here ? Settings->Diagnosis->Diagnostic Logs If you are unable to post them here, feel free to send it 1-1 in our community slack. 

Thanks !

**Comment by njahrckstr** [comment]
which logs specifically?

**Comment by shyam-dev** [comment]
Hello @njahrckstr  - Can you please post the diagnostic logs of the console ?

![Screenshot 2023-02-24 at 10 52 22 AM](https://user-images.githubusercontent.com/1436408/221267139-8178855c-6931-4221-b42d-3e80974b94b5.png)

**Comment by njahrckstr** [comment]
Sorry for the delay. See attached.
[deepfence-logs.tgz](https://github.com/deepfence/ThreatMapper/files/10900733/deepfence-logs.tgz)

**Comment by varunsharma0286** [comment]
Hi @njahrckstr 
I checked the attached logs and looks like the version of ThreatMapper is not the latest. 
Could you please try with the latest version (v1.5.0) and let us know if you still see this issue with the ECR scanning.

**Comment by huirong** [comment]
I hava the same question. 
The version of ThreatMapper is not the latest.
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/7533521/236991882-fb7b6d88-5904-4b8b-a938-eb592df3591e.png">

**Comment by shyam-dev** [comment]
You download the latest version of ThreatMapper using the appropriate deployment from here - https://github.com/deepfence/ThreatMapper/tree/release-1.5/deployment-scripts
