### ISSUE TITLE
level=error msg connect: connection timed out" file="main.go:54"

### ISSUE THREAD

**Issue by rohan-birtia** [deepfence/ThreatMapper#916]
**Describe the bug**
Getting connection timeout .

**To Reproduce**
1. Deploy console management in ec2 instance.
2. From setup instruction deploy Ecs using provided cloud formation template. 
3. Note- EC2 security group is public.

**Screenshots**
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/110599270/222044622-67fd0475-cc42-45cc-9417-d7c0b417a6a7.png">

**Components/Services affected**
Agent

**Comment by ramanan-ravi** [comment]
Hello @rohan-birtia , please check if the management console ip address is open to the cloud scanner
