### ISSUE TITLE
Deepfence Cloud Scanner logs to Deepfence console

### ISSUE THREAD

**Issue by jatin-baweja** [deepfence/ThreatMapper#944]
**Additional context**
Currently, for linux or kubernetes sensor deployment, there is a way on the Deepfence console to download logs for debugging purpose. Similarly, we should be able to download logs for debugging purpose from all cloud scanner deployments.

**Is your feature request related to a problem? Please describe.**
When Deepfence Cloud Scanner is deployed to any account, it is not possible to obtain the logs of the cloud scanner via the Deepfence console. For any debugging purpose, we need to go check the logs on the corresponding cloud to obtain any errors. It would be better, if we can get the logs of the cloud scanner to the Deepfence console, and also enable download of such logs for easier debugging.

**Describe the solution you'd like**
Transport all logs(lets say for 1 hour) from Cloud Scanner to Deepfence Console via a routine task on cloud scanner.

**Describe alternatives you've considered**
Download the cloud scanner logs from the Deepfence console on request only.

**Components/Services**

- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [x] Other (specify)

**Additional context**

**Comment by ibreakthecloud** [comment]
**what are the logs for diagnostic?**
- Steampipe logs
- ECS task logs
- Cloudformation stack/stacksets logs, outputs, etc. (need to figure out the possibility)

**Comment by shyam-dev** [comment]
The logs could also be compressed when sent on the wire to minimize data transfer volume
