### ISSUE TITLE
Registering user first time returns error

### ISSUE THREAD

**Issue by alterEgo123** [deepfence/ThreatMapper#984]
I have installed threatMapper using Helm and all pods are running.

When I try to register user first time, it returns the error `Cannot POST /deepfence/v1.5/users/register`

**Comment by ramanan-ravi** [comment]
Can you check the following pod's logs?
```
docker logs deepfence-api
```

Also have you installed deepfence-router helm chart and connecting to the router service (LB or other service ip)?
