### ISSUE TITLE
Add vulnerability scan support for CentOS 7

### ISSUE THREAD

**Issue by ramanan-ravi** [deepfence/ThreatMapper#995]
- Running vulnerability scan on CentOS 7 does not detect anything
- CentOS 7 security support is available till June 2024, so we should support CentOS 7

**Comment by gnmahanth** [comment]
@jatin-baweja has updated our vulnerability database to include centos 7 data, it should work

**Comment by gnmahanth** [comment]
@shyam-dev centos 7 vulnerability scan on v2 

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/ed32d955-2f16-44dd-abb4-96d21eb36958)

![image](https://github.com/deepfence/ThreatMapper/assets/22050509/5817e625-9bf7-45f8-bb88-bf29ab0daa41)
